(function(g){var window=this;var g4=function(a){var b={languageCode:a.A,languageName:a.B,displayName:g.zO(a),kind:a.C,name:a.D,id:a.Ja,is_servable:a.G,is_default:a.isDefault,is_translateable:a.H,vss_id:a.F};a.o&&(b.translationLanguage=a.o);return b},h4=function(a){return a.o?a.o.languageCode:a.A},$Ca=function(a,b){var c=new g.yO;
c.A=a.A;c.B=a.B;c.D=a.D;c.C=a.C;c.isDefault=!1;c.G=a.G;c.H=a.H;c.F=a.F;c.I=a.I;c.o=b;return c},aDa=function(){this.A=[];
this.o=[]},i4=function(a,b){return b?a.o.concat(a.A):a.o},j4=function(a,b){switch(b.C){case "asr":var c=a.A;
g.Ta(c,(0,g.A)(b.Wv,b))||c.push(b);break;default:c=a.o,g.Ta(c,(0,g.A)(b.Wv,b))||c.push(b)}},k4=function(){g.J.call(this);
this.A=new aDa;this.D=[]},l4=function(a,b,c){k4.call(this,a);
this.o=null;this.D=b.hA;this.C=c},m4=function(){this.ub=[]},n4=function(a,b,c,d,e,f){g.J.call(this);
this.L=a;this.B=b;this.F=new m4;this.o=null;this.I=d;this.M=f;this.A=this.C=null;this.H=c;this.G=e||!1;this.K=new g.V(this.IC,1E3,this);g.K(this,this.K);this.D=new g.lH(this);g.K(this,this.D);g.Y(b).experiments.o("html5_disable_captions_seek_complete")?this.D.R(b,"seekto",this.sD):this.D.R(b,"seekcomplete",this.KO);this.sD(b.getCurrentTime());this.IC()},o4=function(a,b){b-=a.B.Rc();
var c=a.o;a.o=g.Ra(a.H.Mg(b).o);c!=a.o&&a.M&&a.M()},bDa=function(a,b){var c=g.PK(b,a.L,{}).Xa(),d={format:"RAW",
withCredentials:!0};a.G&&(d.responseType="arraybuffer");a.A=g.xG(c,d,3,100).then((0,g.A)(a.sT,a));a.C=b;c=a.F;d=a.C.o[0].A;var e=g.qb(c.ub,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.ub[e-1]&&e<c.ub.length&&1==c.ub[e]-d?(g.ab(c.ub,e),g.ab(c.ub,e-1)):0<e&&1==d-c.ub[e-1]?c.ub[e-1]=d:e<c.ub.length&&1==c.ub[e]-d?c.ub[e]=d:(g.lb(c.ub,e,0,d),g.lb(c.ub,e+1,0,d)))},p4=function(a,b){k4.call(this,g.Y(b));
this.o=a;this.G=b;this.C=null;this.B=!1;this.F=g.jO(g.Y(this.G))&&!this.o.A},cDa=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.RX(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.yO({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},dDa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},eDa=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.RX(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},q4=function(a,b,c,d,e){k4.call(this,e||null);
c=c||g.HF(a).hl||"";c=c.split("_").join("-");this.B=g.JF(a,{hl:c});this.C=b;this.F=!!d;this.G={};this.o=null},r4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.nR.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.D=f;this.A=k},s4=function(a,b,c,d,e){g.nR.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.A=[]},fDa=function(a){a=void 0===a?{}:a;
var b="_"+t4++;return new s4(0,0x8000000000000,0,b,a)},u4=function(a,b,c,d,e,f){var k={};
g.Na(k,b);g.Na(k,a.params);g.Na(k,c);var l={};g.Na(l,b.Sb);a.params.Sb&&g.Na(l,a.params.Sb);g.Na(l,c.Sb);k.Sb=l;g.W.call(this,{J:"div",N:"caption-window",T:{id:"caption-window-"+a.id,dir:1==k.ai?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},P:[{J:"span",N:"captions-text"}]});this.F=[];this.ea=!1;this.D=a;this.K=[];this.O=[];this.Wa=e;this.Sa=f;this.H=this.M=null;this.ia=.96*e;this.za=.96*f;this.B=k;this.Oa=c;this.G=this.o["captions-text"];this.Ia=null!=this.G.style["box-decoration-break"]||
null!=this.G.style["-webkit-box-decoration-break"];this.ha=d/360*16;this.type=0;this.sa=this.ha*gDa(l);a=new g.sH(this.element,!0);g.K(this,a);a.subscribe("dragstart",this.JO,this);a.subscribe("dragmove",this.IO,this);a.subscribe("dragend",this.HO,this);this.ya=this.xa=0;b="";this.B.windowOpacity&&(a=g.Mu(this.B.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.B.windowOpacity+")");a={"background-color":b,display:!1===this.B.isVisible?"none":"","text-align":hDa[this.B.textAlign]};this.Ia&&(a["border-radius"]=
b?this.sa/8+"px":"");if(this.I=2==this.D.params.ai||3==this.D.params.ai)b=this.element,c="vertical-rl",1==this.B.rG&&(c="vertical-lr"),g.de&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.Ph(b,"-o-writing-mode",c),g.Ph(b,"-webkit-writing-mode",c),g.Ph(b,"writing-mode",c),g.Ph(b,"text-orientation","upright"),3==this.D.params.ai&&(g.Ph(b,"text-orientation",""),g.Ph(b,"transform","rotate(180deg)"));g.Ph(this.element,a);switch(this.B.ih){case 0:case 1:case 2:g.T(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.T(this.element,
"ytp-caption-window-bottom")}},gDa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},v4=function(a,b){var c={},d=b.background?b.background:a.B.Sb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.B.Sb.backgroundOpacity;d=g.Mu(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ia&&(c["box-decoration-break"]="clone",c["border-radius"]=a.sa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ha*gDa(b)+"px";d=1;e=b.color||a.B.Sb.color;if(b.color||null!=b.textOpacity)e=g.Mu(e),d=null==b.textOpacity?a.B.Sb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.pA&&(k=e=b.pA);var l=a.ha/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=t;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.eG()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.B.Sb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.dg&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.Ip&&(c.visibility="hidden");return c},iDa=function(a,b,c){a.ea=a.ea||!!c;
var d={};g.Na(d,a.B.Sb);g.Na(d,c||b.A);g.Na(d,a.Oa.Sb);c=a.K[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.Ip==!!c.Ip&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.K.length;e++)if(g.hc(d,a.K[e])){var f=a.O[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.ke("SPAN");g.Ph(f,v4(a,e));a.O[0].appendChild(f);e=1}a.O.length=e;a.K.length=e}else a.O.length=0,a.K.length=0,f=g.ke("SPAN"),g.Ph(f,v4(a,d)),a.G.appendChild(f);k=!d.Ip;e=(c=g.u(b.text))?b.text.split("\n"):
[b.text];for(var l=0;l<e.length;l++){var m=e[l];if(0<l||0==a.F.length||!b.D){if(0<l||0!=a.F.length){var n=g.ke("BR");f.appendChild(n)}k&&a.St(f)}m&&(k?a.M:f).appendChild(c?g.le(m):m)}if(!c)for(k=b.text.querySelectorAll("RT".toString()),c=0;c<k.length;c++)g.Ph(k[c],v4(a,d)),g.Ph(k[c],"font-size","50%");a.K.push(d);a.O.push(f);a.F.push(b)},jDa=function(){},x4=function(){this.B=this.A=this.mode=this.C=0;
this.D=new w4(this);this.F=new w4(this);this.o=[];this.clear()},lDa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Jo:a,
Ko:b,result:0};a=kDa[a];b=kDa[b];if(a&128){if(!(b&128)&&0!=c.o&&c.A==b)return{Jo:a,Ko:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Jo:a,Ko:b,result:2};return{Jo:a,Ko:b,result:3}},nDa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.D.o.clear(),a.F.o.clear()):(a.B=0,mDa(a.D,b,c,d))},oDa=function(a,b){a.o.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.A=d.time;0==d.type?nDa(a,d.kA,d.lA,b):1==d.type&&a.C&496&&mDa(a.F,d.kA,d.lA,b)}a.o.length=0},y4=function(){this.o=0},z4=function(){this.A=this.C=this.o=0},A4=function(){this.timestamp=this.Ie=0},B4=function(a){this.C=[];
for(var b=0;15>=b;b++){this.C[b]=[];for(var c=0;32>=c;c++)this.C[b][c]=new A4}this.o=this.A=this.row=0;this.style=new y4;this.D=a;this.B=0},C4=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.D.A+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var t=a.C[m][p];
if(0!=t.Ie){0==c&&(c=m,d=p);n=String.fromCharCode(t.Ie);var w=t.timestamp;w<e&&(e=w);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Ie||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.A+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.C[k][m],t=p.Ie,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),w=p.timestamp,w<=e&&(e=w),l+=n,p.reset()),32==m||0==t)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},tDa=function(a,b){switch(a){case 0:return pDa[(b&127)-32];
case 1:return qDa[b&15];case 2:return rDa[b&31];case 3:return sDa[b&31]}return 0},D4=function(a){return a.C[a.row][a.A]},E4=function(a,b,c){2<=b&&1<a.A&&(--a.A,D4(a).Ie=0);
var d=D4(a);d.timestamp=a.D.A+0;d.Ie=tDa(b,c);32>a.A&&a.A++},uDa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.C[b+e][f].ph(a.C[c+e][f])},F4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.C[b+d][e].reset()},G4=function(a){a.row=0<a.o?a.o:1;
a.A=1;F4(a,0,15)},H4=function(a){this.B=a;
this.D=0;this.style=new y4;this.F=new B4(a);this.G=new B4(a);this.H=new B4(a);this.A=this.F;this.C=this.G;this.o=this.A},I4=function(a,b,c){var d=a.A,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:C4(d,c),G4(a.A),G4(a.C),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.B.mode=1<<d.B;e?d.A=1:d.o!=b&&(d.o>b?(C4(d,c),F4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},vDa=function(a){a.style.set(1);
a.o=a.C;a.o.o=0;a.o.style=a.style;a.B.mode=1<<a.o.B},wDa=function(a){a.style.set(4);
a.o=a.H;a.o.style=a.style;a.B.mode=1<<a.o.B},w4=function(a){this.A=a;
this.o=new z4;this.D=0;this.C=new H4(a);this.F=new H4(a);this.B=this.C},mDa=function(a,b,c,d){a.o.update();
b=lDa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Jo;c=b.Ko;if(32<=e||!e)a.A.mode&a.A.C&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.o,b&96&&E4(a,0,b),c&96&&E4(a,0,c),0!=b&&0!=c&&3==a.style.o&&C4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.C=e,b.A=c,b.o=2,b=e&8?a.F:a.C,a.B=b,a.A.mode=1<<(a.D<<2)+(b.D<<1)+(4==b.style.o?1:0),(a.A.mode|1<<(a.D<<2)+(b.D<<1)+(4!=b.style.o?1:0))&a.A.C))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;uDa(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));F4(c,b,e)}}c.row=d;c.A=a+1}else switch(e&7){case 1:switch(c&112){case 32:E4(b.o,0,32);break a;case 48:57==c?(b=b.o,D4(b).Ie=0,32>b.A&&b.A++):E4(b.o,1,c&15)}break;case 2:c&32&&E4(b.o,2,c&31);break;case 3:c&32&&E4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:vDa(b);break;
case 33:b=b.o;1<b.A&&(--b.A,D4(b).Ie=0);break;case 36:b=b.o;d=D4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.C[a][c]==d){for(;32>=c;c++)b.C[a][c].reset();break}break;case 37:I4(b,2,d);break;case 38:I4(b,3,d);break;case 39:I4(b,4,d);break;case 40:E4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.A;b.o.o=0;b.o.style=b.style;b.B.mode=1<<b.o.B;break;case 42:d=b.H;d.o=15;d.style.set(4);G4(d);wDa(b);break;case 43:wDa(b);break;case 44:a=b.A;switch(b.style.get()){case 1:case 2:case 3:C4(a,d)}F4(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.A=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;C4(a,d);uDa(a,b,b+1,a.o-1);F4(a,a.row,1)}break;case 46:F4(b.C,0,15);break;case 47:C4(b.A,d);d=b.C;a=b.B.A+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.C[c][e].timestamp=a;d=b.C;b.C=b.A;b.A=d;vDa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.o,32<(b.A+=c&3)&&(b.A=32)}}},J4=function(a){g.J.apply(this,arguments)},K4=function(a){J4.call(this);
this.B={};this.I={};this.K={};this.D="_"+t4++;this.F=a;this.H={};this.A=this.o=null;this.G=!0},L4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},M4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},N4=function(a,b){var c=L4(a,b);
return void 0!=c?c:null},P4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return O4.test(c),c},xDa=function(a,b){var c={},d=b.getAttribute("ws");
g.Na(c,d?a.K[d]:a.F);d=N4(b,"mh");null!=d&&(c.Pv=d);d=N4(b,"ju");null!=d&&(c.textAlign=d);d=N4(b,"pd");null!=d&&(c.ai=d);d=N4(b,"sd");null!=d&&(c.rG=d);d=P4(b,"wfc");null!=d&&(c.windowColor=d);d=L4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},yDa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Na(c,a.I[d]);d=N4(b,"ap");null!=d&&(c.ih=d);d=L4(b,"cc");null!=d&&(c.tA=d);d=L4(b,"ah");null!=d&&(c.eg=d);d=L4(b,"rc");null!=d&&(c.ox=d);d=L4(b,"av");null!=d&&(c.ci=d);return c},zDa=function(a,b,c,d){var e={};
g.Na(e,yDa(a,b));g.Na(e,xDa(a,b));d?g.hc(e,a.F)?(d=a.D,e=a.F):d="_"+t4++:d=b.getAttribute("id")||"_"+t4++;a=L4(b,"t")+c;b=L4(b,"d")||0x8000000000000;return new s4(a,b,0,d,e)},Q4=function(a,b,c,d,e,f,k){u4.call(this,a,b,c,d,e,f,k);
this.type=1},R4=function(a,b,c){this.G=c;
this.version=this.F=this.B=this.o=0;this.A=new DataView(a);this.C=[]},S4=function(a){var b=a.o;
a.o+=1;return a.A.getUint8(b)},T4=function(a){var b=a.o;
a.o+=4;return a.A.getUint32(b)},U4=function(a,b){J4.call(this);
this.A=a;this.track="CC3"==b.B?4:0;this.o=new x4;this.o.C=1<<this.track},BDa=function(a){if(g.u(a))return!1;
a=new R4(a,8,0);return ADa(a)},ADa=function(a){if(!(a.o<a.A.byteLength)||1380139777!=T4(a))return!1;
a.version=S4(a);if(1<a.version)return!1;S4(a);S4(a);S4(a);return!0},V4=function(a,b,c,d,e,f,k){u4.call(this,a,b,c,d,e,f,k);
g.T(this.element,"ytp-caption-window-rollup");this.type=2;this.L=[];this.aa=this.Y=this.ka=0;this.ba=NaN;this.Ea=0;this.Ka=null;this.ma=new g.V(this.xT,433,this);g.K(this,this.ma)},CDa=function(a,b){return(a.I?b.offsetHeight:b.offsetWidth)+1},DDa=function(a){if(isNaN(a.ba)){var b=a.B.tA;
if(b){var c=g.ke("SPAN");g.ye(c,"\u2013".repeat(b));g.Ph(c,v4(a,a.B.Sb));a.G.appendChild(c);a.ba=c.offsetWidth;a.G.removeChild(c)}else a.ba=0}return a.ba},EDa=function(a,b){if(!b)return"";
a.I&&1!=a.D.params.rG&&(b*=-1);return"translate"+(a.I?"X":"Y")+"("+b+"px)"},FDa=function(a){a.L=Array.prototype.slice.call(g.Yd("ytp-rollup-caption-line-wrapper"));
for(var b=a.D.params.ox,c=0,d=0,e=a.L.length-1;c<b&&-1<e;){var f=a.L[e];d+=a.I?f.offsetWidth:f.offsetHeight;c++;e--}a.L.length<b&&(d*=b/a.L.length);a.Y=d;a.aa=Math.max(DDa(a),a.Ea,CDa(a,a.G))},GDa=function(a,b){FDa(a);
var c=a.L.reduce(function(b,c){return(a.I?c.offsetWidth:c.offsetHeight)+b},0);
c=a.Y-c;if(c!=a.ka){var d=0<c&&0==a.ka;b||isNaN(c)||d||(g.T(a.element,"ytp-rollup-mode"),g.tv(a.ma));g.Ph(a.G,"transform",EDa(a,c));a.ka=c}FDa(a)},W4=function(){J4.call(this)},HDa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.dg=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new r4(b,c,d,e.id,p.nodeValue,f||0<n,g.dc(l)?void 0:l);m.push(p);var t=e;g.K(t,p);t.A.push(p)}else t={},g.Na(t,l),HDa(a,b,c,d,e,!0,p,t,m)}},X4=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},IDa=function(a,b,c,d){d=Object.assign({Pv:0},d);
return new s4(a,b,c,"_"+t4++,d)},Y4=function(a){g.J.call(this);
this.A=a;this.o=null},a5=function(a){g.mV.call(this,a);
this.D=g.Y(a);this.C=a.getVideoData();this.ya=g.QU(a);this.L=a;var b=null,c=g.FE("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.oE(c));this.ba=b;this.B={Sb:{}};this.F={Sb:{}};this.K=[];this.V={};this.aa={};this.M=!1;this.sa=g.Kua(this.C,this.L);this.za=!!this.C.captionTracks.length;this.Ea=!!this.C.Rl;this.ma="3"==this.D.C;b=g.eV(a);c=!(!b||!b.Vn());this.xa=!(!b||!b.tj());this.G=this.ma&&c&&!this.sa;this.Y=!this.G&&this.ma&&this.xa&&this.sa;this.A=this.H=this.I=this.O=this.ka=null;this.ga=
new Y4(this.D);g.K(this,this.ga);c=b=this.o=null;this.G||(b=new g.pv(this.IG,void 0,this),g.K(this,b),c=new g.V(this.mV,2E3,this),g.K(this,c));this.ea=b;this.ia=c;this.Z=new g.lH(this);g.K(this,this.Z);this.G||this.Z.R(a,"resize",this.ay);this.Z.R(a,"onPlaybackAudioChange",this.yQ);this.Z.R(a,g.pR("captions"),this.QN,this);this.Z.R(a,"crx_captions",this.RN,this);Z4(this,$4(this,"display-settings")||{})},JDa=function(a){if(1==a.D.mh||1==a.C.mh||"alwayson"==g.RP(a.C,"yt:cc"))return!0;
if(2==a.D.mh){var b=$4(a,"module-enabled");if(null!=b)return!!b}if(a.C.captionTracks.length)var c=a.player.getAudioTrack().Ct;return"ON"==c||"on"==g.RP(a.C,"yt:cc")},b5=function(a,b){if(a.o&&(void 0===b||!b)||!a.C.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.mp||"FORCED_ON"==c.Ct},d5=function(a,b){if(a.A){if(a.H&&a.H.o)return a.H.o;
var c=b;c||(c=a.Ea?!1:a.za?!1:!0);c=i4(a.A.A,c);for(var d=[a.C.lh,a.D.lh,g.RP(a.C,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(h4(c[f])==d[e])return c[f];return a.H&&a.H.Vt?a.H.Vt:(d=c.find(function(a){return a.isDefault}))?d:c[0]||c5(a)}return null},c5=function(a){return a.H&&a.H.mp},e5=function(a){var b=c5(a);
return!!b&&a.o==b},KDa=function(a,b){for(var c=g.eV(a.L).ra().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},g5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.M=c,a.M&&f5(a,"module-enabled",!!b));a.o=b;b5(a)&&(a.o=c5(a));a.load()},LDa=function(a,b){var c=a.ya.getVideoContentRect(!0).height;
if(!c)return null;var d=a.ya.getPlayerSize();switch(null!=b.params.Pv?b.params.Pv:1<b.A.length?1:0){case 1:return new Q4(b,a.B,a.F,c,d.width,d.height,a.D.experiments);case 2:return new V4(b,a.B,a.F,c,d.width,d.height,a.D.experiments);default:return new u4(b,a.B,a.F,c,d.width,d.height,a.D.experiments)}},Z4=function(a,b,c){var d=h5.Sb;
a.B={};g.Na(a.B,h5);a.B.Sb={};g.Na(a.B.Sb,d);a.F={Sb:{}};var e=b.backgroundOverride?a.F:a.B,f=b.background||d.background;O4.test(f);e.Sb.background=f;e=b.colorOverride?a.F:a.B;f=b.color||d.color;O4.test(f);e.Sb.color=f;e=b.windowColorOverride?a.F:a.B;f=b.windowColor||h5.windowColor;O4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Sb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.B;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.Sb.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.dg?3:d.bold?1:d.dg?2:0);f=f.Sb;switch(e){case 1:f.bold=!0;delete f.dg;break;case 2:delete f.bold;f.dg=!0;break;case 3:f.bold=!0;f.dg=!0;break;default:delete f.bold,delete f.dg}e=b.textOpacityOverride?a.F:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Sb.textOpacity=f;e=b.windowOpacityOverride?a.F:a.B;f=b.windowOpacity;null==f&&(f=h5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.F:a.B;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.Sb.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Sb.fontFamily=f;a.loaded&&a.ay();c&&f5(a,"display-settings",b)},NDa=function(a,b){if(b&&!a.I){var c=fDa({ai:0,
lang:"en"});a.I=[c,new r4(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.ZU(a.player,a.I)}else!b&&a.I&&(MDa(a,a.I),a.I=null)},MDa=function(a,b){g.aV(a.player,b);
(0,g.C)(b,function(a){g.bb(this.K,a)},a);
a.ea.Yj()},$4=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},f5=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.wR.prototype.Sl=g.ca(12,function(){for(var a=g.Xd(document,"track",void 0,this.o),b=0;b<a.length;b++)g.qe(a[b])});
g.U_.prototype.Sl=g.ca(11,function(){this.o.Sl()});
g.wR.prototype.Vn=g.ca(10,function(){return!!this.o.textTracks});
g.U_.prototype.Vn=g.ca(9,function(){return this.o.Vn()});
g.wR.prototype.Ml=g.ca(8,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.U_.prototype.Ml=g.ca(7,function(a){this.o.Ml(a)});
g.CQ.prototype.tj=g.ca(6,function(){});
g.wR.prototype.tj=g.ca(5,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.U_.prototype.tj=g.ca(4,function(){return this.o.tj()});
g.yO.prototype.Wv=g.ca(2,function(a){return a?this.toString()==a.toString():!1});
g.II.prototype.Bp=g.ca(1,function(a){return(a=this.sh(a))?a.A:0});
g.yL.prototype.Bp=g.ca(0,function(){return 0});
var ODa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,O4=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(k4,g.J);k4.prototype.rF=function(){return!1};
k4.prototype.W=function(){this.di();g.J.prototype.W.call(this)};
g.r(l4,k4);l4.prototype.Kv=function(a,b,c){b=this.Bm(a,b);var d=(0,g.A)(function(b){this.o=null;c(b.responseText,a)},this);
this.di();this.o=g.WF(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
l4.prototype.Lv=function(a){if(this.C)for(var b=g.q(this.C.captionTracks),c=b.next();!c.done;c=b.next())j4(this.A,c.value);a()};
l4.prototype.Bm=function(a,b){var c=a.Xa(),d={fmt:b};a.o&&(d.tlang=h4(a));return g.JF(c,d)};
l4.prototype.di=function(){this.o&&this.o.abort()};
m4.prototype.contains=function(a){a=g.qb(this.ub,a);return 0<=a||0>a&&1==(-a-1)%2};
m4.prototype.length=function(){return this.ub.length/2};
g.r(n4,g.J);g.h=n4.prototype;g.h.W=function(){g.J.prototype.W.call(this);this.A&&this.A.cancel()};
g.h.sD=function(a){var b=this;if(this.H.Ni())var c=this.D.R(this.B,"progresssync",function(){b.H.index.Nb()&&(b.reset(),b.o=null,o4(b,b.B.getCurrentTime()),b.D.La(c))});
else o4(this,a)};
g.h.KO=function(){o4(this,this.B.getCurrentTime())};
g.h.reset=function(){this.F=new m4;this.A&&(this.A.cancel(),this.A=null)};
g.h.IC=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Vg(a);!a||this.A||this.o&&30<this.o.startTime-this.B.getCurrentTime()||(a=this.o,a=a.o.yk(a),a.o[0].duration&&(this.F.contains(a.o[0].A)||bDa(this,a),this.o=g.Ra(a.o)));this.K.start()};
g.h.sT=function(a){var b=!(this.G?a.response:a.responseText)||400<=a.status,c=g.FL(a);c?(a=g.PK(this.C,this.L,{}),b=this.C,g.KK(b.A,a,c),b.requestId=a.get("req_id"),bDa(this,this.C)):(b||null===this.I||(this.G?this.I(a.response,1E3*(this.C.o[0].startTime+this.B.Rc())):this.I(a.responseText,1E3*(this.C.o[0].startTime+this.B.Rc()))),this.A=this.C=null)};
g.r(p4,k4);g.h=p4.prototype;g.h.Kv=function(a,b,c){this.di();b=dDa(this,a.getId());b||(b=a.A,b=this.o.A?eDa(this,b,"386"):eDa(this,b));if(b){var d=1E3*(b.index.Bp(b.index.rf())-b.index.kd(b.index.rf()));this.C=new n4(new g.fK,this.G,b,function(b,f){c(b,a,f,d)},this.F||g.ZJ(b.info),(0,g.A)(function(){this.C&&this.C.reset();
this.B=!0},this))}};
g.h.rF=function(){var a=this.B;this.B=!1;return a};
g.h.Lv=function(a){var b;this.F?b=[new g.yO({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.yO({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.A?cDa(this,"386"):cDa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())j4(this.A,c.value);a()};
g.h.di=function(){this.C&&(this.C.dispose(),this.C=null)};
g.h.Bm=function(){return""};
g.r(q4,k4);q4.prototype.Kv=function(a,b,c){b=this.Bm(a,b);var d=(0,g.A)(function(b){this.o=null;c(b.responseText,a)},this);
this.di();this.o=g.WF(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
q4.prototype.Lv=function(a){var b=this.B,c={type:"list",tlangs:1,v:this.C,vssids:1};this.F&&(c.asrs=1);b=g.JF(b,c);c=(0,g.A)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var c=g.q(b.getElementsByTagName("track")),d=c.next();!d.done;d=c.next()){var k=d.value;d=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),w="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
j4(this.A,new g.yO({languageCode:d,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:w,vss_id:k,is_default:t}))}b=b.getElementsByTagName("target");c=b.length;for(d=0;d<c;d++)l=b[d].getAttribute("lang_code"),m=b[d].getAttribute("lang_translated"),n=b[d].getAttribute("lang_original"),p=b[d].getAttribute("id"),t="true"==b[d].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:t},this.G[l.languageCode]=l.languageName,this.D.push(l)}a()},this);
this.di();this.o=g.WF(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
q4.prototype.Bm=function(a,b){var c=this.B,d={v:this.C,type:"track",lang:a.A,name:a.D,kind:a.C,fmt:b};a.o&&(d.tlang=h4(a));return c=g.JF(c,d)};
q4.prototype.di=function(){this.o&&this.o.abort()};var hDa=["left","right","center","justify"];var h5={windowColor:"#080808",windowOpacity:0,textAlign:2,ih:7,eg:50,ci:100,Sb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(r4,g.nR);r4.prototype.toString=function(){return g.nR.prototype.toString.call(this)};g.r(s4,g.nR);s4.prototype.toString=function(){return g.nR.prototype.toString.call(this)};
var t4=0;g.r(u4,g.W);g.h=u4.prototype;g.h.JO=function(a,b){var c=g.ei(this.element,this.element.parentElement);this.xa=a-c.x;this.ya=b-c.y;g.T(this.element,"ytp-dragging")};
g.h.IO=function(a,b){var c=g.hi(this.element),d=a-this.xa-.02*this.Wa,e=b-this.ya-.02*this.Sa,f=(d+c.width/2)/this.ia*3;f=Math.floor(g.Id(f,0,2));var k=(e+c.height/2)/this.za*3;k=Math.floor(g.Id(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ia;d=100*g.Id(d,0,1);c=(e+k/2*c.height)/this.za;c=100*g.Id(c,0,1);this.D.params.ih=l;this.D.params.ci=c;this.D.params.eg=d;this.B.ih=l;this.B.ci=c;this.B.eg=d;this.GF()};
g.h.HO=function(){g.Dr(this.element,"ytp-dragging")};
g.h.GF=function(){this.pj(this.F)};
g.h.Xb=function(){return this.type};
g.h.pj=function(a){var b=Math.min(this.uB(),this.ia),c=this.tB(),d="";3==this.D.params.ai&&(d="rotate(180deg)");g.Ph(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.it(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.B.eg+2;d=this.B.ih;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.G.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.B.ci+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Ph(this.element,a)};
g.h.it=function(a){var b;for(b=0;b<a.length&&a[b]==this.F[b];b++);if(this.ea||this.F.length>b)b=0,this.ea=!1,this.F=[],this.K=[],this.O=[],this.M=this.H=null,g.oe(this.G);for(;b<a.length;b++)iDa(this,a[b])};
g.h.uB=function(){return 0};
g.h.tB=function(){return 0};
g.h.St=function(a){this.H=g.ke("SPAN");this.H.appendChild(g.le("\u00a0"));this.M=g.ke("SPAN");g.T(this.M,"caption-visual-line");this.H.appendChild(this.M);this.H.appendChild(g.le("\u00a0"));a.appendChild(this.H)};
g.h.toString=function(){return g.W.prototype.toString.call(this)};jDa.prototype.D=function(){};x4.prototype.clear=function(){this.B=this.A=this.mode=0;this.o=[];this.reset()};
x4.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var kDa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];y4.prototype.set=function(a){this.o=a};
y4.prototype.get=function(){return this.o};
z4.prototype.clear=function(){this.o=0};
z4.prototype.update=function(){this.o=2==this.o?1:0};
z4.prototype.matches=function(a,b){return 0!=this.o&&a==this.C&&b==this.A};
A4.prototype.ph=function(a){this.Ie=a.Ie;this.timestamp=a.timestamp};
A4.prototype.reset=function(){this.timestamp=this.Ie=0};
B4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.C[b][c];a=0==d.Ie?a+"_":a+String.fromCharCode(d.Ie)}a+="\n"}return a};
B4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.C[b][c].reset();this.B=a;this.o=0;this.A=this.row=1};
var pDa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],qDa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],rDa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],sDa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];H4.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.A=this.F;this.C=this.G;this.o=this.A;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.H.reset((a<<2)+(b<<1)+1)};
w4.prototype.reset=function(a){this.D=a;this.o.clear();this.B=this.C;this.C.reset(a,0);this.F.reset(a,1)};g.r(J4,g.J);J4.prototype.reset=function(){};g.r(K4,J4);K4.prototype.reset=function(){this.H={};this.A=this.o=null;this.G=!0};
K4.prototype.C=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.B,l={},m=c.getAttribute("p");m&&g.Na(l,this.B[m]);m=M4(c,"b");null!=m&&(l.bold=
m);m=M4(c,"i");null!=m&&(l.dg=m);m=M4(c,"u");null!=m&&(l.underline=m);m=N4(c,"et");null!=m&&(l.charEdgeStyle=m);m=N4(c,"of");null!=m&&(l.offset=m);m=P4(c,"bc");null!=m&&(l.background=m);m=P4(c,"ec");null!=m&&(l.pA=m);m=P4(c,"fc");null!=m&&(l.color=m);m=N4(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=L4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=L4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=L4(c,"fo");void 0!=m&&(l.textOpacity=m/255);c=N4(c,"rb");null!=c&&(l.tV=c);k[d]=l;break;case "ws":d=
c.getAttribute("id");this.K[d]=xDa(this,c);break;case "wp":d=c.getAttribute("id"),this.I[d]=yDa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=zDa(this,d,e,!1);g.K(this,this.o);(d=this.H[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.H[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.D;m=!!M4(d,"a");n=(L4(d,"t")||0)+n;var p=L4(d,"d")||5E3;m||
(!this.G&&this.A&&this.A.windowId==l&&this.A.end>n&&(this.A.end=n),this.A&&"\n"==this.A.text&&(this.A.text=""));var t=m?6:5,w=this.B[d.getAttribute("p")],z=d.childNodes;z.length&&(this.G=null!=d.getAttribute("d"));for(var E=0;E<z.length;E++){var G=z[E];0<E&&(m=!0);var N=void 0;1==G.nodeType&&(N=G);if(N&&"s"==N.tagName)if((G=this.B[N.getAttribute("p")])&&1==G.tV){G=n;var O=p,ra=l,jb=m,eb=t;var zc=N;var ub=z[E+1],wd=z[E+2],Zb=z[E+3];zc.getAttribute("p");L4(zc,"t");L4(ub,"t");L4(wd,"t");L4(Zb,"t");N=
g.ke("RUBY");zc=zc.textContent;var Jd=g.ke("SPAN");Jd.innerText=zc;N.appendChild(Jd);ub.getAttribute("p");Jd=g.ke("RP");zc=ub.textContent;Jd.innerText=zc;N.appendChild(Jd);wd.getAttribute("p");zc=wd.textContent;ub=g.ke("RT");ub.innerText=zc;N.appendChild(ub);Zb.getAttribute("p");zc=Zb.textContent;Zb=g.ke("RP");Zb.innerText=zc;N.appendChild(Zb);G=new r4(G,O,eb,ra,N,jb,null);E+=3}else Zb=N,G=n,O=p,ra=l,jb=m,eb=t,N=Zb.textContent?Zb.textContent:"",zc=this.B[Zb.getAttribute("p")],Zb=L4(Zb,"t")||0,G=new r4(G+
Zb,O-Zb,eb,ra,N,jb,zc);else G=new r4(n,p,t,l,G.textContent||"",m,w);k.push(G);this.A=G}if(0<k.length)for(k[0].windowId==this.D&&(this.o=zDa(this,d,e,!0),g.K(this,this.o),c.push(this.o)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,l=this.o,g.K(l,k),l.A.push(k),c.push(k)}e=c}else e=[];return e};g.r(Q4,u4);Q4.prototype.it=function(a){var b=this.D.A;u4.prototype.it.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.A==e)var d=f;else{d={};g.Na(d,c.A);g.Na(d,PDa);var e=c.A;var f=d}iDa(this,c,d)}};
var PDa={Ip:!0};g.r(R4,jDa);R4.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+t4++;c=c/1E3-this.G;d=d/1E3-this.G;a=new s4(c,d-c,5,f,{textAlign:0,ih:0,eg:2.5*b,ci:5.33*a});e=new r4(c,d-c,5,f,e);this.C.push(a);this.C.push(e)}};
g.r(U4,J4);U4.prototype.C=function(a){a=new R4(a,a.byteLength,this.A);if(ADa(a)){for(;a.o<a.A.byteLength;)for(0==a.version?a.B=T4(a)*(1E3/45):1==a.version&&(a.B=4294967296*T4(a)+T4(a)),a.F=S4(a);0<a.F;a.F--){var b=S4(a),c=S4(a),d=S4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.B,type:this.track,kA:c,lA:d,order:b.o.length}))}oDa(this.o,a);return a.C}return[]};
U4.prototype.reset=function(){this.o.clear()};g.r(V4,u4);g.h=V4.prototype;g.h.GF=function(){g.uv(this.ma)};
g.h.xT=function(){g.Dr(this.element,"ytp-rollup-mode");this.pj(this.Ka,!0)};
g.h.tB=function(){return this.I?this.aa:this.Y};
g.h.uB=function(){return this.I?this.Y:this.aa};
g.h.St=function(a){u4.prototype.St.call(this,a);g.T(this.H,"ytp-rollup-caption-line-wrapper");g.Ph(this.H,"display","inline-block");g.Ph(this.M,"display","inline-block")};
g.h.pj=function(a,b){this.Ka=a;if(this.D.params.ox){for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));this.Ea=this.aa;this.Y=this.aa=0;u4.prototype.pj.call(this,a);GDa(this,b);u4.prototype.pj.call(this,a)}else u4.prototype.pj.call(this,a)};g.r(W4,J4);
W4.prototype.C=function(a,b){for(var c=[],d=a.split(QDa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!RDa.test(f)){var l=i5.exec(f);if(l&&4<=l.length){var m=X4(l[1]),n=X4(l[2])-m;m+=k;var p,t=p=void 0,w=void 0,z=void 0,E=l[3];l={textAlign:2};E=g.q(E?E.split(" "):[]);for(var G=E.next();!G.done;G=E.next())if(G=G.value.split(":"),2==G.length){var N=G[1];switch(G[0]){case "line":G=N.split(",");G[0].endsWith("%")&&(z=G[0],l.ci=Number.parseInt(z,10),2==G.length&&(w=G[1].trim()));break;case "position":G=N.split(",");
t=G[0];l.eg=Number.parseInt(t,10);2==G.length&&(p=G[1].trim());break;case "align":switch(N){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.ci=100,w||(w="end"));if(!t)switch(l.textAlign){case 0:l.eg=0;break;case 1:l.eg=100;break;default:l.eg=50}t=0;switch(w){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(p){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.ih=0>t||8<t?7:t;p=l;f=f.substring(i5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=IDa(m,n,5,t),n=new r4(m,n,5,k.id,p,!1,g.dc(f)?void 0:f),c.push(k),c.push(n),g.K(k,n),k.A.push(n);else for(w=p.split(SDa),1==w.length?(p=5,t=IDa(m,n,p,t)):(z=p=6,t=Object.assign({tA:32},t),t=new s4(m,n,z,"_"+t4++,t)),c.push(t),z=m,l=0;l<w.length;l++)E=w[l],0==l%2?(G=g.nt("<html>"+E+"</html>"),G.getElementsByTagName("parsererror").length?
(N=G.createElement("span"),N.appendChild(G.createTextNode(E))):N=G.firstChild,HDa(this,z,n-(z-m),p,t,0<l,N,f,c)):z=X4(E)+k}i5.lastIndex=0}}return c};
var RDa=/^NOTE/,QDa=/(?:\r\n|\r|\n){2,}/,i5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),SDa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(Y4,g.J);Y4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
Y4.prototype.reset=function(){this.o&&this.o.reset()};
Y4.prototype.W=function(){this.clear();g.J.prototype.W.call(this)};g.r(a5,g.mV);g.h=a5.prototype;g.h.W=function(){if(this.G||this.Y){var a=g.eV(this.L);a&&a.Sl()}else NDa(this,!1);g.mV.prototype.W.call(this)};
g.h.Qn=function(){return this.ma?this.G||this.Y:b5(this)?!0:JDa(this)};
g.h.load=function(){g.mV.prototype.load.call(this);this.H=this.player.getAudioTrack();if(this.A)this.o&&(this.ga.clear(),this.G?KDa(this,!0):3!=this.player.getPresentingPlayerType()&&this.A.Kv(this.o,"srv3",(0,g.A)(this.iU,this))),this.o&&!e5(this)?this.player.Ba("captionschanged",g4(this.o)):this.player.Ba("onCaptionsTrackListChanged");else{var a;this.sa?a=new p4(this.C.ua,this.player):this.za?a=new l4(this.D,this.C,this.player.getAudioTrack()):a=new q4(this.C.Rl,this.C.videoId,this.C.lh||this.D.lh||
g.RP(this.C,"yt:cc_default_lang")||this.D.za,this.C.At,this.D);this.A=a;g.K(this,this.A);a.Lv((0,g.A)(this.hU,this))}};
g.h.unload=function(){this.G&&this.o?KDa(this,!1):(this.ia&&g.vv(this.ia),g.bV(this.player,"captions"),this.K=[],this.A&&this.A.di(),this.ga.clear(),this.I&&g.ZU(this.player,this.I),this.ay());g.mV.prototype.unload.call(this);var a=g.Z(this.player.app);a&&a.B&&g.AQ(a.B.C);this.player.Ba("captionschanged",{})};
g.h.hU=function(){var a;this.M||JDa(this)?a=d5(this,this.M):b5(this)&&(a=c5(this));if(this.G||this.Y){for(var b=i4(this.A.A,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.zO(e),srclang:h4(e),id:e.toString()};this.Y||(f.src=this.A.Bm(e,"vtt"));e==a&&(f["default"]=1);c.push(g.ie("TRACK",f))}g.eV(this.L).Ml(c);a=g.eV(this.L).ra();this.xa&&this.Z.R(a.textTracks,"change",this.jU)}else!this.o&&a&&g5(this,a),this.player.Ba("onCaptionsTrackListChanged"),this.player.Ba("onApiChange")};
g.h.jU=function(){for(var a=g.eV(this.L).ra().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=i4(this.A.A,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.o:null)!=b&&g5(this,b,!0)};
g.h.jW=function(){!this.o&&this.G||this.unload()};
g.h.iU=function(a,b,c,d){if(a){this.A.rF()&&(this.K=[],g.bV(this.L,"captions"),this.ea.Yj(),this.ga.reset());var e=this.ga;c=c||0;d=d||0;if(!g.u(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.cJ(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!BDa(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.u(a)){if("WEBVTT"==a.substring(0,6)){b=a;var w=c;e.o||(e.o=new W4);var z=e.o.C(b,w);.01>Math.random()&&g.dF(Error("Deprecated subtitles format in web player: WebVTT"));var E=z}else b:{z=a;w=g.nt(z);if(!w||!w.firstChild)throw Error("Invalid caption track data: "+
z);if("timedtext"==w.firstChild.tagName){if(3==parseInt(w.firstChild.getAttribute("format"),10)){if(!e.o){z={};var G=h4(b);G&&(z.lang=G,ODa.test(G)&&(z.ai=1));e.o=new K4(z,e.A)}E=e.o.C(w,c);break b}var N=Error("Unsupported subtitles format in web player (Format2)");N.params=z;throw N;}if("transcript"==w.firstChild.tagName)throw Error("Unsupported subtitles format in web player (Format1): "+z);throw Error("Invalid caption track data: "+z);}var O=E}else{E=a;w=c;G=d;if(!BDa(E))throw Error("Invalid binary caption track data");
e.o||(e.o=new U4(G,b));O=e.o.C(E,w)}var ra=O}catch(jb){g.bF(jb),e.clear(),ra=[]}else ra=[];g.ZU(this.player,ra);!this.M||this.Y||e5(this)||g.ZN(this.D)||g.$N(this.D)||(g.vv(this.ia),ra=fDa({ih:0,eg:5,ci:5,ox:2,textAlign:0,ai:0,lang:"en"}),this.O=[ra],e=["Click "," for settings"],this.ka||(O=new g.iQ(g.rta()),g.K(this,O),this.ka=O.element),O=ra.end-ra.start,(b=g.zO(this.o))&&this.O.push(new r4(ra.start,O,0,ra.id,b)),this.O.push(new r4(ra.start,O,0,ra.id,e[0]),new r4(ra.start,O,0,ra.id,this.ka,!0),
new r4(ra.start,O,0,ra.id,e[1],!0)),g.ZU(this.player,this.O),g.tv(this.ia));!this.M||this.Y||e5(this)||(f5(this,"module-enabled",!0),this.H&&(this.H.o=this.o),(ra=g.Z(this.player.app))&&ra.B&&g.AQ(ra.B.C));this.M=!1}};
g.h.QN=function(a){this.K.push(a);this.ea.Yj()};
g.h.RN=function(a){g.bb(this.K,a);this.A instanceof p4&&this.A.F&&g.aV(this.player,[a]);this.ea.Yj()};
g.h.eV=function(a){if(a instanceof s4){var b=this.V[a.id];b&&b.D!=a&&(b.dispose(),delete this.V[a.id],b=null);b||(b=LDa(this,a))&&(this.V[a.id]=b)}else b=a.windowId,this.aa[b]||(this.aa[b]=[]),this.aa[b].push(a)};
g.h.mV=function(){MDa(this,this.O);this.O=null};
g.h.IG=function(){this.ea.stop();g.ec(this.aa);this.K.sort(g.oR);var a=this.K;if(this.I){var b=(0,g.re)(a,function(a){return-1==this.I.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.eV,this);g.Mb(this.V,function(a,b){this.aa[b]?(a.element.parentNode||g.dV(this.player,a.element,4),a.pj(this.aa[b])):(a.dispose(),delete this.V[b])},this)};
g.h.rV=function(){Z4(this,{},!0)};
g.h.YK=function(){var a=h5.Sb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.dg?3:a.bold?1:a.dg?2:0,textOpacity:a.textOpacity,windowColor:h5.windowColor,windowOpacity:h5.windowOpacity};var b=$4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.MG=function(a,b){var c={};g.Na(c,$4(this,"display-settings"));g.Na(c,a);Z4(this,c,b);this.player.U("captionssettingschanged")};
g.h.ay=function(){!this.G&&this.loaded&&(g.Mb(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.IG())};
g.h.Gc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Id(b,-2,4);this.MG({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&g5(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.D.Ob&&f5(this,"module-enabled",!!b);break;case "track":if(!this.A)return{};if(b){if(this.G)break;if(!g.Ja(b))break;if(g.dc(b)){g5(this,null,!0);break}for(var d=i4(this.A.A,!0),e=0;e<d.length;e++){var f=d[e];f.A!=b.languageCode||c&&f.B!=b.languageName||(c=b.translationLanguage?$Ca(f,b.translationLanguage):
f)}!c||c==this.o&&this.loaded||g5(this,c,!0)}else return this.loaded&&this.o&&!e5(this)?g4(this.o):{};return"";case "tracklist":return this.A?(0,g.I)(i4(this.A.A,!(!b||!b.includeAsr)),function(a){return g4(a)}):[];
case "translationLanguages":return this.A?this.A.D:[];case "sampleSubtitles":this.G||void 0==b||NDa(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.D.Ob&&a.push("stickyLoading");return a};
g.h.Ng=function(){var a=this.o;return a?{cc:a.F}:{}};
g.h.zG=function(){this.loaded&&this.o&&!e5(this)?(f5(this,"module-enabled",!1),this.unload(),b5(this,!0)&&g5(this,c5(this),!1)):g5(this,e5(this)||!this.o?d5(this,!0):this.o,!0)};
g.h.yQ=function(){var a=e5(this);b5(this,a)?g5(this,this.player.getAudioTrack().mp,!1):this.C.captionTracks.length&&(this.loaded&&this.unload(),this.Qn()&&(a?g5(this,d5(this),!1):this.load()))};g.WZ.captions=a5;})(_yt_player);
