(function(){'use strict';var f,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={I:!0},ea={};try{ea.__proto__=da;ca=ea.I;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.v=b.prototype}var ia="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ka(a,b){if(b){var c=ia;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}function la(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
ka("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=la(this,a,"startsWith"),e=b.length,g=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var h=0;h<g&&c<e;)if(b[c++]!=a[h++])return!1;return h>=g}});ka("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}});ka("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==la(this,a,"includes").indexOf(a,c||0)}});var l=this;function m(a){return void 0!==a}
function n(a){return"string"==typeof a}function p(a){return"number"==typeof a}function ma(){}
function q(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function r(a){return"array"==q(a)}function t(a){var b=q(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function na(a,b,c){return a.call.apply(a.bind,arguments)}
function oa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?v=na:v=oa;return v.apply(null,arguments)}
function pa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}function w(a,b){function c(){}c.prototype=b.prototype;a.v=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ca=function(a,c,g){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var qa;var ra=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(n(a))return n(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},x=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=n(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},sa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=
a.length,d=[],e=0,g=n(a)?a.split(""):a,h=0;h<c;h++)if(h in g){var k=g[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function ta(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function ua(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function va(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var wa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function xa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<wa.length;g++)c=wa[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function y(){this.a="";this.b=ya}f=y.prototype;f.u=!0;f.m=function(){return this.a};f.C=!0;f.j=function(){return 1};f.da=function(a,b){var c=za.exec(Aa(this)),d=c[3]||"";a=c[1]+Ba("?",c[2]||"",a)+Ba("#",d,b);b=new y;b.a=a;return b};function Aa(a){return a instanceof y&&a.constructor===y&&a.b===ya?a.a:"type_error:TrustedResourceUrl"}var za=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,ya={};
function Ba(a,b,c){if(null==c)return b;if(n(c))return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=r(e)?e:[e];for(var g=0;g<e.length;g++){var h=e[g];null!=h&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(h)))}}return b};var Ca=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Da(a,b){if(b)a=a.replace(Ea,"&amp;").replace(Fa,"&lt;").replace(Ga,"&gt;").replace(Ha,"&quot;").replace(Ia,"&#39;").replace(Ja,"&#0;");else{if(!Ka.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ea,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Fa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ga,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ha,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ia,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ja,"&#0;"))}return a}
var Ea=/&/g,Fa=/</g,Ga=/>/g,Ha=/"/g,Ia=/'/g,Ja=/\x00/g,Ka=/[\x00&<>"']/;function La(a,b){return a<b?-1:a>b?1:0};function z(){this.a="";this.b=Ma}z.prototype.u=!0;z.prototype.m=function(){return this.a};z.prototype.C=!0;z.prototype.j=function(){return 1};var Ma={};function Na(a){var b=new z;b.a=a;return b}Na("about:blank");var A;a:{var Oa=l.navigator;if(Oa){var Pa=Oa.userAgent;if(Pa){A=Pa;break a}}A=""};function B(){this.a="";this.c=Qa;this.b=null}B.prototype.C=!0;B.prototype.j=function(){return this.b};B.prototype.u=!0;B.prototype.m=function(){return this.a};function C(a){return a instanceof B&&a.constructor===B&&a.c===Qa?a.a:"type_error:SafeHtml"}function Ra(a){if(a instanceof B)return a;var b="object"==typeof a,c=null;b&&a.C&&(c=a.j());a=Da(b&&a.u?a.m():String(a));return D(a,c)}
function Sa(a){function b(a){r(a)?x(a,b):(a=Ra(a),d+=C(a),a=a.j(),0==c?c=a:0!=a&&c!=a&&(c=null))}var c=0,d="";x(arguments,b);return D(d,c)}var Qa={};function D(a,b){var c=new B;c.a=a;c.b=b;return c}D("<!DOCTYPE html>",0);D("",0);var Ta=D("<br>",0);function E(a){return a=Da(a,void 0)};var F="StopIteration"in l?l.StopIteration:{message:"StopIteration",stack:""};function G(){}G.prototype.next=function(){throw F;};G.prototype.i=function(){return this};function Ua(a){if(a instanceof G)return a;if("function"==typeof a.i)return a.i(!1);if(t(a)){var b=0,c=new G;c.next=function(){for(;;){if(b>=a.length)throw F;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function Va(a,b){if(t(a))try{x(a,b,void 0)}catch(c){if(c!==F)throw c;}else{a=Ua(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==F)throw c;}}}function Wa(a){if(t(a))return ta(a);a=Ua(a);var b=[];Va(a,function(a){b.push(a)});return b};var H={},Xa={},Ya={},Za={};function I(){throw Error("Do not instantiate directly");}I.prototype.A=null;I.prototype.toString=function(){return this.o};I.prototype.a=function(){if(this.f===Za)return Ra(this.toString());if(this.f!==H)throw Error("Sanitized content was not of kind TEXT or HTML.");return D(this.toString(),this.A||null)};I.prototype.b=function(){if(this.f!==Xa)throw Error("Sanitized content was not of kind URI.");return Na(this.toString())};function $a(){I.call(this)}w($a,I);
$a.prototype.f=H;function ab(a){ab[" "](a);return a}ab[" "]=ma;function bb(a,b){var c=cb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var db=-1!=A.indexOf("Opera"),J=-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"),eb=-1!=A.indexOf("Edge"),fb=-1!=A.indexOf("Gecko")&&!(-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"))&&!(-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"))&&-1==A.indexOf("Edge"),K=-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"),gb=-1!=A.indexOf("Macintosh");function hb(){var a=l.document;return a?a.documentMode:void 0}var ib;
a:{var jb="",kb=function(){var a=A;if(fb)return/rv:([^\);]+)(\)|;)/.exec(a);if(eb)return/Edge\/([\d\.]+)/.exec(a);if(J)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(K)return/WebKit\/(\S+)/.exec(a);if(db)return/(?:Version)[ \/]?(\S+)/.exec(a)}();kb&&(jb=kb?kb[1]:"");if(J){var lb=hb();if(null!=lb&&lb>parseFloat(jb)){ib=String(lb);break a}}ib=jb}var mb=ib,cb={};
function L(a){return bb(a,function(){for(var b=0,c=Ca(String(mb)).split("."),d=Ca(String(a)).split("."),e=Math.max(c.length,d.length),g=0;0==b&&g<e;g++){var h=c[g]||"",k=d[g]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=La(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||La(0==h[2].length,0==k[2].length)||La(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var M;var nb=l.document;
M=nb&&J?hb()||("CSS1Compat"==nb.compatMode?parseInt(mb,10):5):void 0;function ob(a){if(null!=a)switch(a.A){case 1:return 1;case -1:return-1;case 0:return 0}return null}function pb(a){return null!=a&&a.f===H?a:a instanceof B?N(C(a),a.j()):N(E(String(String(a))),ob(a))}var N=function(a){function b(a){this.o=a}b.prototype=a.prototype;return function(a,d){a=new b(String(a));void 0!==d&&(a.A=d);return a}}($a);function qb(a){return null!=a&&a.f===H?String(String(a.o).replace(rb,"").replace(sb,"&lt;")).replace(tb,ub):E(String(a))}
function vb(a){null!=a&&a.f===Xa||null!=a&&a.f===Ya?a=String(a).replace(wb,xb):a instanceof z?a=String(a instanceof z&&a.constructor===z&&a.b===Ma?a.a:"type_error:SafeUrl").replace(wb,xb):a instanceof y?a=String(Aa(a)).replace(wb,xb):(a=String(a),a=yb.test(a)?a.replace(wb,xb):"about:invalid#zSoyz");return a}
var zb={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function ub(a){return zb[a]}
var Ab={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",
")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB",
"\uff3d":"%EF%BC%BD"};function xb(a){return Ab[a]}var tb=/[\x00\x22\x27\x3c\x3e]/g,wb=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,yb=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,rb=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,sb=/</g;function Bb(){return N('<div class="devsite-snackbar-snack" type="loading"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Loading</div><div class="devsite-snackbar-action"><devsite-spinner single-color="#ffffff"></devsite-spinner></div></div></div>')}
function Cb(){return N('<div class="devsite-snackbar-snack" type="refresh"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">A new version is available</div><button class="devsite-snackbar-action">Refresh</button></div></div>')}
function Db(){return N('<div class="devsite-snackbar-snack" type="error"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Something went wrong. Please try again.</div><button class="devsite-snackbar-action">Retry</button></div></div>')}function Eb(){return N('<div class="devsite-snackbar-snack" type="copied-to-clipboard"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Copied to clipboard</div></div></div>')}
function Fb(a){a=a||{};a=a.J;a='<div class="devsite-snackbar-snack" type="cookie-notification"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">We serve cookies on this site to analyse traffic, remember your preferences, and optimise your experience.'+('</div><a href="'+(a?qb(vb(a)):"//policies.google.com/technologies/cookies")+'" class="devsite-snackbar-link button">');return N(a+'More details</a><button class="devsite-snackbar-action">OK</button></div></div>')}
function Gb(){return N('<div class="devsite-snackbar-snack" type="support-attachment-error"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Unsupported file type.</div><button class="devsite-snackbar-action">OK</button></div></div>')}
function Hb(a){var b=a.message,c=a.link,d=a.T;a='<div class="devsite-snackbar-snack" type="'+qb(a.Y)+'"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">'+pb(b)+'</div><button class="devsite-snackbar-action">';a=a+"No, thanks"+('</button><a href="'+qb(vb(c))+'" class="devsite-snackbar-link button" target="_blank">');a=d?a+pb(d):a+"OK";return N(a+"</a></div></div>")}
function Ib(a){var b=a.X;a='<div class="devsite-snackbar-snack" type="custom"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">'+pb(a.message)+"</div>";b&&(a+='<button class="devsite-snackbar-action">OK</button>');return N(a+"</div></div>")};function O(a){var b=HTMLElement.call(this)||this;a&&(n(a)&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ha(O,HTMLElement);f=O.prototype;f.connectedCallback=function(){Jb(this)};f.F=function(){return""};function Jb(a){var b=a.F();!a.hasAttribute("ds-is")&&b&&a.setAttribute("ds-is",b)}f.Tb=function(){console.warn(this.tagName,"has not implemented update")};
f.fa=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};f.Fb=function(a,b){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&this.appendChild(document.importNode(b,!0))};O.prototype.connectedCallback=O.prototype.connectedCallback;var Kb=!J||9<=Number(M),Lb=!fb&&!J||J&&9<=Number(M)||fb&&L("1.9.1"),Mb=J&&!L("9"),Nb=J||db||K;var Ob=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div");a.innerHTML="<div><div></div></div>";var b=a.firstChild.firstChild;a.innerHTML="";return!b.parentElement});function Pb(a,b){if(Ob())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=b};function P(a,b){this.a=m(a)?a:0;this.b=m(b)?b:0}f=P.prototype;f.kb=function(){return new P(this.a,this.b)};f.ha=function(a){return a instanceof P&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};f.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};f.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};f.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
f.mb=function(a,b){a instanceof P?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),p(b)&&(this.b+=b));return this};f.lb=function(a,b){b=p(b)?b:a;this.a*=a;this.b*=b;return this};f.Kb=function(a,b){a=a*Math.PI/180;b=b||new P(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function Qb(a,b){this.width=a;this.height=b}f=Qb.prototype;f.nb=function(){return new Qb(this.width,this.height)};f.Ha=function(){return Math.max(this.width,this.height)};f.Ua=function(){return Math.min(this.width,this.height)};f.Gb=function(){return 2*(this.width+this.height)};f.aspectRatio=function(){return this.width/this.height};f.vb=function(){return!(this.width*this.height)};f.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
f.la=function(a){return this.width<=a.width&&this.height<=a.height};f.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};f.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Rb(a,b){var c=p(void 0)?void 0:b;a.width*=b;a.height*=c;return a}f.Mb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Rb(this,a)};
f.Nb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Rb(this,a)};function Sb(a){return a?new Q(R(a)):qa||(qa=new Q)}function Tb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Ub(document,"*",a,b);return d||null}
function Vb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var g=d=0,h;h=b[g];g++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(g=d=0;h=b[g];g++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=ra(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Ub(a,b,c,d){var e=d||a,g=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(g||c)?e.querySelector(g+(c?"."+c:"")):Vb(a,b,c,d)[0]||null}function Wb(a,b){ua(b,function(b,d){b&&"object"==typeof b&&b.u&&(b=b.m());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Xb.hasOwnProperty(d)?a.setAttribute(Xb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}
var Xb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Yb(a){a=a.document;a=Zb(a)?a.documentElement:a.body;return new Qb(a.clientWidth,a.clientHeight)}function $b(a){return a.scrollingElement?a.scrollingElement:!K&&Zb(a)?a.documentElement:a.body||a.documentElement}
function ac(a){return a.parentWindow||a.defaultView}function bc(a,b,c,d){function e(c){c&&b.appendChild(n(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];t(g)&&!cc(g)?x(dc(g)?ta(g):g,e):e(g)}}function Zb(a){return"CSS1Compat"==a.compatMode}function gc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function hc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function ic(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}
function cc(a){return u(a)&&0<a.nodeType}function jc(a){return u(a)&&1==a.nodeType}function kc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function lc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return mc(b,a)}function mc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}
function R(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function nc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else gc(a),a.appendChild(R(a).createTextNode(String(b)))}function oc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||oc(a,b,c,d))return!0;a=a.nextSibling}return!1}
var pc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},qc={IMG:" ",BR:"\n"};function rc(a){return sc(a)&&tc(a)}function sc(a){return J&&!L("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function tc(a){a=a.tabIndex;return p(a)&&0<=a&&32768>a}
function uc(a){if(Mb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];vc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Mb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function vc(a,b,c){if(!(a.nodeName in pc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in qc)b.push(qc[a.nodeName]);else for(a=a.firstChild;a;)vc(a,b,c),a=a.nextSibling}function dc(a){if(a&&"number"==typeof a.length){if(u(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==q(a))return"function"==typeof a.item}return!1}
function wc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return xc(a,function(a){var b;(b=!e||a.nodeName==e)&&!(b=!c)&&(b=n(a.className))&&(a=a.className.split(/\s+/),b=0<=ra(a,c));return b},!0,d)}function xc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function Q(a){this.a=a||l.document||document}f=Q.prototype;f.ya=Sb;f.Ob=function(a){this.a=a};f.ua=function(){return this.a};
f.M=function(a){return n(a)?this.a.getElementById(a):a};f.Sa=function(a){return n(a)?this.a.getElementById(a):a};f.$=Q.prototype.M;f.ab=function(a,b){return(b||this.a).getElementsByTagName(String(a))};f.N=function(a,b,c){return Vb(this.a,a,b,c)};f.Aa=function(a,b,c){return Ub(this.a,a,b,c)};f.Ba=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Vb(document,"*",a,b)};f.za=function(a,b){return Tb(a,b||this.a)};
f.Ta=function(a,b){return Tb(a,b||this.a)};f.aa=Q.prototype.N;f.Qb=Wb;f.Wa=function(a){return Yb(a||ac(this.a)||window)};f.va=function(){var a=ac(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Yb(a).height,Zb(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
f.K=function(a,b,c){var d=this.a,e=arguments,g=String(e[0]),h=e[1];if(!Kb&&h&&(h.name||h.type)){g=["<",g];h.name&&g.push(' name="',E(h.name),'"');if(h.type){g.push(' type="',E(h.type),'"');var k={};xa(k,h);delete k.type;h=k}g.push(">");g=g.join("")}g=d.createElement(g);h&&(n(h)?g.className=h:r(h)?g.className=h.join(" "):Wb(g,h));2<e.length&&bc(d,g,e,2);return g};f.ba=Q.prototype.K;f.$a=function(a){return this.a.createTextNode(String(a))};
f.ga=function(a,b,c){var d=this.a;c=!!c;for(var e=d.createElement("TABLE"),g=e.appendChild(d.createElement("TBODY")),h=0;h<a;h++){for(var k=d.createElement("TR"),ec=0;ec<b;ec++){var fc=d.createElement("TD");c&&nc(fc,"\u00a0");k.appendChild(fc)}g.appendChild(k)}return e};
f.Lb=function(a){var b=this.a;var c=b.createElement("DIV");J?(a=Sa(Ta,a),Pb(c,C(a)),c.removeChild(c.firstChild)):Pb(c,C(a));if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};f.tb=function(){return Zb(this.a)};f.xa=function(){return $b(this.a)};
f.wa=function(){var a=this.a,b=$b(a);a=ac(a);return J&&L("10")&&a.pageYOffset!=b.scrollTop?new P(b.scrollLeft,b.scrollTop):new P(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};f.na=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};f.Ya=function(a,b){a.appendChild(b)};f.Xa=function(a,b){bc(R(a),a,arguments,1)};f.Za=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
f.Jb=gc;f.rb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};f.qb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};f.pb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};f.bb=hc;f.cb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};f.ma=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return hc(a)}};
f.sa=function(a){return Lb&&void 0!=a.children?a.children:sa(a.childNodes,function(a){return 1==a.nodeType})};f.Ca=function(a){return m(a.firstElementChild)?a.firstElementChild:ic(a.firstChild,!0)};f.Fa=function(a){return m(a.lastElementChild)?a.lastElementChild:ic(a.lastChild,!1)};f.Ia=function(a){return m(a.nextElementSibling)?a.nextElementSibling:ic(a.nextSibling,!0)};f.Qa=function(a){return m(a.previousElementSibling)?a.previousElementSibling:ic(a.previousSibling,!1)};
f.Ja=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};f.Ra=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};f.yb=cc;f.ub=jc;f.Ab=function(a){return u(a)&&a.window==a};f.Pa=function(a){var b;if(Nb&&!(J&&L("9")&&!L("10")&&l.SVGElement&&a instanceof l.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return jc(b)?b:null};
f.contains=kc;
f.ea=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(J&&!(9<=Number(M))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,g=b.parentNode;return e==g?mc(a,b):!c&&kc(e,b)?-1*lc(a,b):!d&&kc(g,a)?lc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:g.sourceIndex)}d=R(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(l.Range.START_TO_END,a)};f.ia=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var g=[],h=arguments[b];h;)g.unshift(h),h=h.parentNode;d.push(g);e=Math.min(e,g.length)}g=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return g;g=h}return g};f.Oa=R;f.Da=function(a){return a.contentDocument||a.contentWindow.document};
f.Ea=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?ac(c):window}else d=null;b=d}return b}catch(e){}return null};f.Rb=nc;f.Na=function(a){if("outerHTML"in a)return a.outerHTML;var b=R(a).createElement("DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};f.ja=function(a,b){var c=[];return oc(a,b,c,!0)?c[0]:void 0};f.ka=function(a,b){var c=[];oc(a,b,c,!1);return c};f.xb=rc;f.Pb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
f.wb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!sc(a)||tc(a)):rc(a))&&J){var c;"function"!=q(a.getBoundingClientRect)||J&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};f.Va=uc;f.La=function(a){return uc(a).length};
f.Ma=function(a,b){b=b||R(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(uc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
f.Ka=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in pc))if(3==e.nodeType){var g=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=g.length}else if(e.nodeName in qc)d+=qc[e.nodeName].length;else for(g=e.childNodes.length-1;0<=g;g--)a.push(e.childNodes[g]);u(c)&&(c.Ib=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};f.zb=dc;f.qa=wc;f.pa=function(a,b,c){return wc(a,null,b,c)};f.oa=xc;f.ra=function(a){return a.getContext("2d")};function yc(){this.g=this.g;this.b=this.b}f=yc.prototype;f.g=!1;f.R=function(){return this.g};f.ta=yc.prototype.R;f.D=function(){this.g||(this.g=!0,this.B())};f.Hb=function(a){a=pa(zc,a);this.g?m(void 0)?a.call(void 0):a():(this.b||(this.b=[]),this.b.push(m(void 0)?v(a,void 0):a))};f.B=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function zc(a){a&&"function"==typeof a.D&&a.D()};var Ac=!J||9<=Number(M),Bc=!J||9<=Number(M),Cc=J&&!L("9"),Dc=function(){if(!l.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{l.addEventListener("test",ma,b),l.removeEventListener("test",ma,b)}catch(c){}return a}();function Ec(a,b){this.type=a;this.b=this.target=b;this.V=this.h=!1;this.Z=!0}Ec.prototype.stopPropagation=function(){this.h=!0};Ec.prototype.c=function(){this.V=!0;this.Z=!1};var Fc;Fc=K?"webkitTransitionEnd":db?"otransitionend":"transitionend";function S(a,b){Ec.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.S=this.H=0;this.key="";this.s=this.G=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.U=null;this.W=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(fb){a:{try{ab(b.nodeName);
var e=!0;break a}catch(g){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.H=K||void 0!==a.offsetX?a.offsetX:a.layerX,this.S=K||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.G=a.keyCode||0;this.key=a.key||"";this.s=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.W=gb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType=n(a.pointerType)?a.pointerType:Gc[a.pointerType]||"";this.U=a.state;this.a=a;a.defaultPrevented&&this.c()}}w(S,Ec);var Hc=[1,4,2],Gc={2:"touch",3:"pen",4:"mouse"};
S.prototype.Ub=function(){return(Ac?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Hc[0]))&&!(K&&gb&&this.ctrlKey)};S.prototype.stopPropagation=function(){S.v.stopPropagation.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};S.prototype.c=function(){S.v.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Cc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Ic="closure_listenable_"+(1E6*Math.random()|0),Jc=0;function Kc(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Jc;this.l=this.w=!1}function Lc(a){a.l=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Mc(a){this.src=a;this.a={};this.b=0}f=Mc.prototype;f.gb=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};f.add=function(a,b,c,d,e){var g=a.toString();a=this.a[g];a||(a=this.a[g]=[],this.b++);var h=Nc(a,b,d,e);-1<h?(b=a[h],c||(b.w=!1)):(b=new Kc(b,this.src,g,!!d,e),b.w=c,a.push(b));return b};
f.ib=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Nc(e,b,c,d);return-1<b?(Lc(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};f.jb=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Lc(d[e]);delete this.a[c];this.b--}return b};f.Ga=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
f.hb=function(a,b){var c=m(a),d=c?a.toString():"",e=m(b);return va(this.a,function(a){for(var g=0;g<a.length;++g)if(!(c&&a[g].type!=d||e&&a[g].capture!=b))return!0;return!1})};function Nc(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.l&&g.listener==b&&g.capture==!!c&&g.b==d)return e}return-1};var Oc="closure_lm_"+(1E6*Math.random()|0),Pc={},Qc=0;function Rc(a,b,c,d,e){if(d&&d.once)return T(a,b,c,d,e);if(r(b)){for(var g=0;g<b.length;g++)Rc(a,b[g],c,d,e);return null}c=Sc(c);return a&&a[Ic]?U(a,b,c,u(d)?!!d.capture:!!d,e):Tc(a,b,c,!1,d,e)}
function Tc(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var h=u(e)?!!e.capture:!!e,k=Uc(a);k||(a[Oc]=k=new Mc(a));c=k.add(b,c,d,h,g);if(c.a)return c;d=Vc();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Dc||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Wc(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Qc++;return c}
function Vc(){var a=Xc,b=Bc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function T(a,b,c,d,e){if(r(b)){for(var g=0;g<b.length;g++)T(a,b[g],c,d,e);return null}c=Sc(c);return a&&a[Ic]?a.H(b,c,u(d)?!!d.capture:!!d,e):Tc(a,b,c,!0,d,e)}
function Yc(a){if(!p(a)&&a&&!a.l){var b=a.src;if(b&&b[Ic])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Wc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Qc--;if(c=Uc(b)){d=a.type;if(d in c.a){var e=c.a[d],g=ra(e,a),h;(h=0<=g)&&Array.prototype.splice.call(e,g,1);h&&(Lc(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[Oc]=null)}else Lc(a)}}}function Wc(a){return a in Pc?Pc[a]:Pc[a]="on"+a}
function Zc(a,b,c,d){var e=!0;if(a=Uc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.l&&(g=$c(g,d),e=e&&!1!==g)}return e}function $c(a,b){var c=a.listener,d=a.b||a.src;a.w&&Yc(a);return c.call(d,b)}
function Xc(a,b){if(a.l)return!0;if(!Bc){if(!b)a:{b=["window","event"];for(var c=l,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new S(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.h&&0<=e;e--){b.b=d[e];var g=Zc(d[e],a,!0,b);c=c&&g}for(e=0;!b.h&&e<d.length;e++)b.b=d[e],g=Zc(d[e],a,!1,b),c=
c&&g}return c}return $c(a,new S(b,this))}function Uc(a){a=a[Oc];return a instanceof Mc?a:null}var ad="__closure_events_fn_"+(1E9*Math.random()>>>0);function Sc(a){if("function"==q(a))return a;a[ad]||(a[ad]=function(b){return a.handleEvent(b)});return a[ad]};function V(a){yc.call(this);this.c=a;this.a={}}w(V,yc);var bd=[];function cd(a,b,c){U(a,b,"click",c,void 0)}f=V.prototype;f.Cb=function(a,b,c,d,e){return U(this,a,b,c,d,e)};function U(a,b,c,d,e,g){r(c)||(c&&(bd[0]=c.toString()),c=bd);for(var h=0;h<c.length;h++){var k=Rc(b,c[h],d||a.handleEvent,e||!1,g||a.c||a);if(!k)break;a.a[k.key]=k}return a}f.fb=function(a,b,c,d){return dd(this,a,b,c,d)};f.Bb=function(a,b,c,d,e){return dd(this,a,b,c,d,e)};
function dd(a,b,c,d,e,g){if(r(c))for(var h=0;h<c.length;h++)dd(a,b,c[h],d,e,g);else{b=T(b,c,d||a.handleEvent,e,g||a.c||a);if(!b)return a;a.a[b.key]=b}return a}f.Db=function(a,b,c,d){U(b,a,c,d,this.c||this);return this};f.Eb=function(a,b,c,d,e){U(b,a,c,d,e||this.c||this);return this};f.eb=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function ed(a,b,c,d,e,g){if(r(c))for(var h=0;h<c.length;h++)ed(a,b,c[h],d,e,g);else d=d||a.handleEvent,e=u(e)?!!e.capture:!!e,g=g||a.c||a,d=Sc(d),e=!!e,b&&b[Ic]?c=b.G(c,d,e,g):b?(b=Uc(b))?(c=b.a[c.toString()],b=-1,c&&(b=Nc(c,d,e,g)),c=-1<b?c[b]:null):c=null:c=null,c&&(Yc(c),delete a.a[c.key])}f.Sb=function(a,b,c,d,e){ed(b,a,c,d,e||this.c||this,this);return this};function fd(a){ua(a.a,function(a,c){this.a.hasOwnProperty(c)&&Yc(a)},a);a.a={}}f.B=function(){V.v.B.call(this);fd(this)};
f.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function W(a,b){b=a(b||gd,void 0,void 0);a=Sb().a.createElement("DIV");b=hd(b);Pb(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}function hd(a){if(!u(a))return String(a);if(a instanceof I){if(a.f===H)return a.o;if(a.f===Za)return E(a.o)}return"zSoyz"}var gd={};function id(){};function jd(){}w(jd,id);jd.prototype.L=function(){var a=0;Va(this.i(!0),function(){a++});return a};jd.prototype.O=function(){var a=Wa(this.i(!0)),b=this;x(a,function(a){b.a.removeItem(a)})};function kd(a){this.a=a}w(kd,jd);f=kd.prototype;f.sb=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};f.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};f.get=function(a){a=this.a.getItem(a);if(!n(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};f.L=function(){return this.a.length};
f.i=function(a){var b=0,c=this.a,d=new G;d.next=function(){if(b>=c.length)throw F;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!n(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};f.O=function(){this.a.clear()};f.key=function(a){return this.a.key(a)};function ld(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a}w(ld,kd);function X(){var a=O.call(this)||this;a.h=-1;a.s=new V(a);a.b=new ld;a.a=[];return a}ha(X,O);f=X.prototype;f.F=function(){return"snackbar"};f.connectedCallback=function(){Jb(this);U(this.s,document.body,"devsite-show-custom-snackbar-msg",this.P,void 0)};f.disconnectedCallback=function(){fd(this.s)};
f.P=function(a){var b=this;this.setAttribute("type","custom");a=a.a.detail;var c=!!a.showClose,d=W(Ib,{message:a.msg,X:c});c&&T(d.querySelector(".devsite-snackbar-action"),"click",function(){Y(b,d)});Z(this,d,!c)};
f.attributeChangedCallback=function(a,b,c){if("type"==a){switch(b){case "loading":Y(this,this.querySelector('*[type^="loading"]'));break;case "refresh":Y(this,this.querySelector('*[type^="refresh"]'));break;case "error":Y(this,this.querySelector('*[type^="error"]'));break;case "copied-to-clipboard":Y(this,this.querySelector('*[type^="copied-to-clipboard"]'));break;case "cookie-notification":md(this);break;case "support-attachment-error":nd(this);break;case "custom":nd(this)}null!=b&&b.startsWith("notification-")&&
od(this);c&&(c.includes(",")&&(this.a=c.split(","),c=this.a.shift()),pd(this,c))}};function pd(a,b){switch(b){case "loading":if(!a.querySelector('*[type^="loading"]')){var c=W(Bb);Z(a,c)}break;case "refresh":qd(a);break;case "error":rd(a);break;case "copied-to-clipboard":c=W(Eb);Z(a,c,!0);break;case "cookie-notification":sd(a);break;case "support-attachment-error":td(a)}b.startsWith("notification-")&&ud(a,b)}f.ob=function(){Y(this,this.querySelector('*[type^="custom"]'))};
function Z(a,b,c){c=void 0===c?!1:c;a.appendChild(b);window.requestAnimationFrame(function(){vd(a,b,c)})}function vd(a,b,c){c=void 0===c?!1:c;window.clearTimeout(a.h);a.c?Y(a,a.c,b,c):(a.c=b,window.requestAnimationFrame(function(){b.setAttribute("show","")}),c&&(a.h=window.setTimeout(function(){a.removeAttribute("type");Y(a,b)},5E3)))}function qd(a){var b=W(Cb);Rc(b.querySelector(".devsite-snackbar-action"),"click",function(){window.location.reload()});Z(a,b)}
function rd(a){var b=W(Db);Rc(b.querySelector(".devsite-snackbar-action"),"click",function(){window.location.reload()});Z(a,b)}function Y(a,b,c,d){c=void 0===c?null:c;d=void 0===d?!1:d;b&&(T(b,Fc,function(){hc(b);a.c=null;if(c)vd(a,c,d);else{var e=a.a.length?a.a.shift():null;null!==e&&pd(a,e)}}),b.removeAttribute("show"))}
function sd(a){if(a.b.get("devsite-eu-cookie")){var b=a.a.length?a.a.shift():null;null!==b&&pd(a,b)}else a.hasAttribute("data-cookie-policy")?(b=a.getAttribute("data-cookie-policy"),b=W(Fb,{J:b})):b=W(Fb),T(b.querySelector(".devsite-snackbar-action"),"click",function(){a.b.set("devsite-eu-cookie","1");md(a)}),Z(a,b)}function md(a){Y(a,a.querySelector('*[type^="cookie-notification"]'))}function td(a){var b=W(Gb);Z(a,b);T(b.querySelector(".devsite-snackbar-action"),"click",function(){nd(a)})}
function nd(a){Y(a,a.querySelector('*[type^="support-attachment-error"]'))}
function ud(a,b){var c=a.getAttribute(b+"-message"),d=a.getAttribute(b+"-link"),e=a.getAttribute(b+"-link-txt"),g=a.hasAttribute(b+"-store-key");if(c&&d){var h="devsite-notification"+d;if(!g||!a.b.get(h)){b=W(Hb,{Y:b,message:c,link:d,T:e});Z(a,b);var k=new V(b);cd(k,b,function(b){b.stopPropagation();if(b.target.classList.contains("devsite-snackbar-link")||b.target.classList.contains("devsite-snackbar-action"))g&&a.b.set(h,"1"),od(a),fd(k)})}}}
function od(a){Y(a,a.querySelector('*[type^="notification"]'))}ia.Object.defineProperties(X,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["type"]}}});X.prototype.attributeChangedCallback=X.prototype.attributeChangedCallback;X.prototype.disconnectedCallback=X.prototype.disconnectedCallback;X.prototype.connectedCallback=X.prototype.connectedCallback;try{window.customElements.define("devsite-snackbar",X)}catch(a){console.warn("devsite.app.customElement.DevsiteSnackBar",a)};}).call(this);
