(function(){'use strict';var e,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={G:!0},ea={};try{ea.__proto__=da;ca=ea.G;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.O=b.prototype}var ia="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ka(a,b){if(b){var c=ia;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}function la(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ma(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:la(a)}}
ka("Promise",function(a){function b(a){this.b=0;this.h=void 0;this.a=[];var b=this.f();try{a(b.resolve,b.reject)}catch(C){b.reject(C)}}function c(){this.a=null}function d(a){return a instanceof b?a:new b(function(b){b(a)})}if(a)return a;c.prototype.b=function(a){if(null==this.a){this.a=[];var b=this;this.f(function(){b.h()})}this.a.push(a)};var f=ia.setTimeout;c.prototype.f=function(a){f(a,0)};c.prototype.h=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;++b){var c=
a[b];a[b]=null;try{c()}catch(D){this.g(D)}}}this.a=null};c.prototype.g=function(a){this.f(function(){throw a;})};b.prototype.f=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.N),reject:a(this.g)}};b.prototype.N=function(a){if(a===this)this.g(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.P(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.s(a):this.j(a)}};
b.prototype.s=function(a){var b=void 0;try{b=a.then}catch(C){this.g(C);return}"function"==typeof b?this.R(b,a):this.j(a)};b.prototype.g=function(a){this.l(2,a)};b.prototype.j=function(a){this.l(1,a)};b.prototype.l=function(a,b){if(0!=this.b)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.b);this.b=a;this.h=b;this.m()};b.prototype.m=function(){if(null!=this.a){for(var a=0;a<this.a.length;++a)g.b(this.a[a]);this.a=null}};var g=new c;b.prototype.P=function(a){var b=this.f();
a.u(b.resolve,b.reject)};b.prototype.R=function(a,b){var c=this.f();try{a.call(b,c.resolve,c.reject)}catch(D){c.reject(D)}};b.prototype.then=function(a,c){function d(a,b){return"function"==typeof a?function(b){try{f(a(b))}catch(Rb){g(Rb)}}:b}var f,g,h=new b(function(a,b){f=a;g=b});this.u(d(a,f),d(c,g));return h};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.u=function(a,b){function c(){switch(d.b){case 1:a(d.h);break;case 2:b(d.h);break;default:throw Error("Unexpected state: "+
d.b);}}var d=this;null==this.a?g.b(c):this.a.push(c)};b.resolve=d;b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(b,c){for(var f=ma(a),g=f.next();!g.done;g=f.next())d(g.value).u(b,c)})};b.all=function(a){var c=ma(a),f=c.next();return f.done?d([]):new b(function(a,b){function g(b){return function(c){h[b]=c;k--;0==k&&a(h)}}var h=[],k=0;do h.push(void 0),k++,d(f.value).u(g(h.length-1),b),f=c.next();while(!f.done)})};return b});
ka("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}});var l=this;function m(a){return void 0!==a}function n(a){return"string"==typeof a}function p(a){return"number"==typeof a}
function q(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function r(a){var b=q(a);return"array"==b||"object"==b&&"number"==typeof a.length}function t(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var na=Date.now||function(){return+new Date};
function oa(a,b){function c(){}c.prototype=b.prototype;a.O=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.V=function(a,c,g){for(var d=Array(arguments.length-2),f=2;f<arguments.length;f++)d[f-2]=arguments[f];return b.prototype[c].apply(a,d)}};var pa;var u=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(n(a))return n(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},v=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=n(a)?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},qa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=
a.length,d=[],f=0,g=n(a)?a.split(""):a,h=0;h<c;h++)if(h in g){var k=g[h];b.call(void 0,k,h,a)&&(d[f++]=k)}return d};function ra(a){return Array.prototype.concat.apply([],arguments)}function sa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var ta=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function ua(a,b){if(b)a=a.replace(va,"&amp;").replace(wa,"&lt;").replace(xa,"&gt;").replace(ya,"&quot;").replace(za,"&#39;").replace(Aa,"&#0;");else{if(!Ba.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(va,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(wa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(xa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ya,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(za,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Aa,"&#0;"))}return a}
var va=/&/g,wa=/</g,xa=/>/g,ya=/"/g,za=/'/g,Aa=/\x00/g,Ba=/[\x00&<>"']/;function w(a,b){return-1!=a.indexOf(b)}function Ca(a,b){return a<b?-1:a>b?1:0};var x;a:{var Da=l.navigator;if(Da){var Ea=Da.userAgent;if(Ea){x=Ea;break a}}x=""};function Fa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var Ga="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ha(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<Ga.length;g++)c=Ga[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Ia(a){return a=ua(a,void 0)};function Ja(a,b){var c=Ka;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var La=w(x,"Opera"),y=w(x,"Trident")||w(x,"MSIE"),Ma=w(x,"Edge"),Na=w(x,"Gecko")&&!(w(x.toLowerCase(),"webkit")&&!w(x,"Edge"))&&!(w(x,"Trident")||w(x,"MSIE"))&&!w(x,"Edge"),Oa=w(x.toLowerCase(),"webkit")&&!w(x,"Edge");function Pa(){var a=l.document;return a?a.documentMode:void 0}var Qa;
a:{var Ra="",Sa=function(){var a=x;if(Na)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ma)return/Edge\/([\d\.]+)/.exec(a);if(y)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Oa)return/WebKit\/(\S+)/.exec(a);if(La)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Sa&&(Ra=Sa?Sa[1]:"");if(y){var Ta=Pa();if(null!=Ta&&Ta>parseFloat(Ra)){Qa=String(Ta);break a}}Qa=Ra}var Ua=Qa,Ka={};
function z(a){return Ja(a,function(){for(var b=0,c=ta(String(Ua)).split("."),d=ta(String(a)).split("."),f=Math.max(c.length,d.length),g=0;0==b&&g<f;g++){var h=c[g]||"",k=d[g]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=Ca(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||Ca(0==h[2].length,0==k[2].length)||Ca(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var A;var Va=l.document;
A=Va&&y?Pa()||("CSS1Compat"==Va.compatMode?parseInt(Ua,10):5):void 0;function B(){this.b="";this.f=Wa}B.prototype.w=!0;B.prototype.v=function(){return this.b};B.prototype.D=!0;B.prototype.a=function(){return 1};var Wa={};function Xa(a){var b=new B;b.b=a;return b}Xa("about:blank");function E(){this.b="";this.g=Ya;this.f=null}E.prototype.D=!0;E.prototype.a=function(){return this.f};E.prototype.w=!0;E.prototype.v=function(){return this.b};function Za(a){if(a instanceof E&&a.constructor===E&&a.g===Ya)return a.b;q(a);return"type_error:SafeHtml"}function $a(a){if(a instanceof E)return a;var b="object"==typeof a,c=null;b&&a.D&&(c=a.a());a=ua(b&&a.w?a.v():String(a));return F(a,c)}
function ab(a){function b(a){"array"==q(a)?v(a,b):(a=$a(a),d+=Za(a),a=a.a(),0==c?c=a:0!=a&&c!=a&&(c=null))}var c=0,d="";v(arguments,b);return F(d,c)}var Ya={};function F(a,b){var c=new E;c.b=a;c.f=b;return c}F("<!DOCTYPE html>",0);F("",0);var bb=F("<br>",0);var cb="StopIteration"in l?l.StopIteration:{message:"StopIteration",stack:""};function db(){}db.prototype.next=function(){throw cb;};db.prototype.a=function(){return this};function G(a,b){this.b={};this.a=[];this.g=this.f=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof G)for(c=a.o(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}e=G.prototype;e.i=function(){H(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};e.o=function(){H(this);return this.a.concat()};
e.nb=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(I(this.b,c)&&this.b[c]==a)return!0}return!1};e.ob=function(a,b){if(this===a)return!0;if(this.f!=a.f)return!1;b=b||eb;H(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function eb(a,b){return a===b}e.pb=function(){return 0==this.f};e.mb=function(){this.b={};this.g=this.f=this.a.length=0};
function H(a){if(a.f!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];I(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.f!=a.a.length){var f={};for(c=b=0;b<a.a.length;)d=a.a[b],I(f,d)||(a.a[c++]=d,f[d]=1),b++;a.a.length=c}}e.get=function(a,b){return I(this.b,a)?this.b[a]:b};e.set=function(a,b){I(this.b,a)||(this.f++,this.a.push(a),this.g++);this.b[a]=b};e.forEach=function(a,b){for(var c=this.o(),d=0;d<c.length;d++){var f=c[d],g=this.get(f);a.call(b,g,f,this)}};
e.Tb=function(){for(var a=new G,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};e.Sb=function(){H(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};e.wa=function(){return fb(this,!0)};e.Oa=function(){return fb(this,!1)};function fb(a,b){H(a);var c=0,d=a.g,f=new db;f.next=function(){if(d!=a.g)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw cb;var f=a.a[c++];return b?f:a.b[f]};return f}
function I(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function gb(a){if(a.i&&"function"==typeof a.i)return a.i();if(n(a))return a.split("");if(r(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function hb(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(r(a)||n(a))v(a,b,c);else{if(a.o&&"function"==typeof a.o)var d=a.o();else if(a.i&&"function"==typeof a.i)d=void 0;else if(r(a)||n(a)){d=[];for(var f=a.length,g=0;g<f;g++)d.push(g)}else for(g in d=[],f=0,a)d[f++]=g;f=gb(a);g=f.length;for(var h=0;h<g;h++)b.call(c,f[h],d&&d[h],a)}};var ib=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function jb(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),f=null;if(0<=d){var g=a[c].substring(0,d);f=a[c].substring(d+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};function J(a,b){this.b=this.m=this.j="";this.g=null;this.l=this.f="";this.h=this.s=!1;if(a instanceof J){this.h=m(b)?b:a.h;kb(this,a.j);var c=a.m;K(this);this.m=c;c=a.b;K(this);this.b=c;lb(this,a.g);c=a.f;K(this);this.f=c;L(this,mb(a.a));a=a.l;K(this);this.l=a}else a&&(c=String(a).match(ib))?(this.h=!!b,kb(this,c[1]||"",!0),a=c[2]||"",K(this),this.m=M(a),a=c[3]||"",K(this),this.b=M(a,!0),lb(this,c[4]),a=c[5]||"",K(this),this.f=M(a,!0),L(this,c[6]||"",!0),a=c[7]||"",K(this),this.l=M(a)):(this.h=!!b,
this.a=new N(null,this.h))}e=J.prototype;e.toString=function(){var a=[],b=this.j;b&&a.push(O(b,nb,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.m)&&a.push(O(b,nb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.g,null!=c&&a.push(":",String(c));if(c=this.f)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(O(c,"/"==c.charAt(0)?ob:pb,!0));(c=this.a.toString())&&a.push("?",c);(c=this.l)&&a.push("#",O(c,qb));return a.join("")};
e.resolve=function(a){var b=new J(this),c=!!a.j;c?kb(b,a.j):c=!!a.m;if(c){var d=a.m;K(b);b.m=d}else c=!!a.b;c?(d=a.b,K(b),b.b=d):c=null!=a.g;d=a.f;if(c)lb(b,a.g);else if(c=!!a.f){if("/"!=d.charAt(0))if(this.b&&!this.f)d="/"+d;else{var f=b.f.lastIndexOf("/");-1!=f&&(d=b.f.substr(0,f+1)+d)}f=d;if(".."==f||"."==f)d="";else if(w(f,"./")||w(f,"/.")){d=0==f.lastIndexOf("/",0);f=f.split("/");for(var g=[],h=0;h<f.length;){var k=f[h++];"."==k?d&&h==f.length&&g.push(""):".."==k?((1<g.length||1==g.length&&""!=
g[0])&&g.pop(),d&&h==f.length&&g.push("")):(g.push(k),d=!0)}d=g.join("/")}else d=f}c?(K(b),b.f=d):c=""!==a.a.toString();c?L(b,mb(a.a)):c=!!a.l;c&&(a=a.l,K(b),b.l=a);return b};function kb(a,b,c){K(a);a.j=c?M(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function lb(a,b){K(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.g=b}else a.g=null}function L(a,b,c){K(a);b instanceof N?(a.a=b,rb(a.a,a.h)):(c||(b=O(b,sb)),a.a=new N(b,a.h));return a}e.Pb=function(a,b){return L(this,a,b)};
e.ka=function(){return M(this.a.toString())};e.Va=function(){return this.a.toString()};e.Nb=function(a,b){K(this);"array"==q(b)||(b=[String(b)]);tb(this.a,a,b);return this};e.Ga=function(a){return this.a.i(a)};e.qb=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.g&&null==a.g||this.g==a.g)};e.Cb=function(){K(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^na()).toString(36);K(this);this.a.set("zx",a);return this};
e.Wa=function(a){K(this);P(this.a,a);return this};e.Qb=function(a){this.s=a;return this};e.Ab=function(){return this.s};function K(a){if(a.s)throw Error("Tried to modify a read-only Uri");}e.Xa=function(a){this.h=a;this.a&&rb(this.a,a);return this};function M(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function O(a,b,c){return n(a)?(a=encodeURI(a).replace(b,ub),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}
function ub(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var nb=/[#\/\?@]/g,pb=/[#\?:]/g,ob=/[#\?]/g,sb=/[#\?@]/g,qb=/#/g;function N(a,b){this.b=this.a=null;this.f=a||null;this.g=!!b}function Q(a){a.a||(a.a=new G,a.b=0,a.f&&jb(a.f,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}e=N.prototype;e.Ta=function(){Q(this);return this.b};e.add=function(a,b){Q(this);this.f=null;a=R(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
function P(a,b){Q(a);b=R(a,b);I(a.a.b,b)&&(a.f=null,a.b-=a.a.get(b).length,a=a.a,I(a.b,b)&&(delete a.b[b],a.f--,a.g++,a.a.length>2*a.f&&H(a)))}e.Qa=function(){this.a=this.f=null;this.b=0};e.Ua=function(){Q(this);return 0==this.b};function vb(a,b){Q(a);b=R(a,b);return I(a.a.b,b)}e.Ra=function(a){var b=this.i();return 0<=u(b,a)};e.forEach=function(a,b){Q(this);this.a.forEach(function(c,d){v(c,function(c){a.call(b,c,d,this)},this)},this)};
e.o=function(){Q(this);for(var a=this.a.i(),b=this.a.o(),c=[],d=0;d<b.length;d++)for(var f=a[d],g=0;g<f.length;g++)c.push(b[d]);return c};e.i=function(a){Q(this);var b=[];if(n(a))vb(this,a)&&(b=ra(b,this.a.get(R(this,a))));else{a=this.a.i();for(var c=0;c<a.length;c++)b=ra(b,a[c])}return b};e.set=function(a,b){Q(this);this.f=null;a=R(this,a);vb(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
e.get=function(a,b){if(!a)return b;a=this.i(a);return 0<a.length?String(a[0]):b};function tb(a,b,c){P(a,b);0<c.length&&(a.f=null,a.a.set(R(a,b),sa(c)),a.b+=c.length)}e.toString=function(){if(this.f)return this.f;if(!this.a)return"";for(var a=[],b=this.a.o(),c=0;c<b.length;c++){var d=b[c],f=encodeURIComponent(String(d));d=this.i(d);for(var g=0;g<d.length;g++){var h=f;""!==d[g]&&(h+="="+encodeURIComponent(String(d[g])));a.push(h)}}return this.f=a.join("&")};
e.Z=function(a){Q(this);this.a.forEach(function(b,c){0<=u(a,c)||P(this,c)},this);return this};function mb(a){var b=new N;b.f=a.f;a.a&&(b.a=new G(a.a),b.b=a.b);return b}function R(a,b){b=String(b);a.g&&(b=b.toLowerCase());return b}function rb(a,b){b&&!a.g&&(Q(a),a.f=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(P(this,b),tb(this,c,a))},a));a.g=b}e.Sa=function(a){for(var b=0;b<arguments.length;b++)hb(arguments[b],function(a,b){this.add(b,a)},this)};var wb={},xb={},yb={};function S(){throw Error("Do not instantiate directly");}S.prototype.f=null;S.prototype.toString=function(){return this.b};S.prototype.g=function(){if(this.a===yb)return $a(this.toString());if(this.a!==wb)throw Error("Sanitized content was not of kind TEXT or HTML.");return F(this.toString(),this.f||null)};S.prototype.h=function(){if(this.a!==xb)throw Error("Sanitized content was not of kind URI.");return Xa(this.toString())};function zb(){S.call(this)}oa(zb,S);
zb.prototype.a=wb;var Ab=function(a){function b(a){this.b=a}b.prototype=a.prototype;return function(a,d){a=new b(String(a));void 0!==d&&(a.f=d);return a}}(zb),Bb=/['()]/g;function Cb(a){return"%"+a.charCodeAt(0).toString(16)};var Db=!y||9<=Number(A),Eb=!Na&&!y||y&&9<=Number(A)||Na&&z("1.9.1"),Fb=y&&!z("9"),Gb=y||La||Oa;var Hb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div");a.innerHTML="<div><div></div></div>";var b=a.firstChild.firstChild;a.innerHTML="";return!b.parentElement});function Ib(a,b){if(Hb())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=b};function T(a,b){this.a=m(a)?a:0;this.b=m(b)?b:0}e=T.prototype;e.gb=function(){return new T(this.a,this.b)};e.hb=function(a){return a instanceof T&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};e.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};e.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};e.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
e.jb=function(a,b){a instanceof T?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),p(b)&&(this.b+=b));return this};e.ib=function(a,b){b=p(b)?b:a;this.a*=a;this.b*=b;return this};e.Hb=function(a,b){a=a*Math.PI/180;b=b||new T(0,0);var c=this.a,d=this.b,f=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*f-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*f+b.b};function Jb(a,b){this.width=a;this.height=b}e=Jb.prototype;e.kb=function(){return new Jb(this.width,this.height)};e.ya=function(){return Math.max(this.width,this.height)};e.Ma=function(){return Math.min(this.width,this.height)};e.Eb=function(){return 2*(this.width+this.height)};e.aspectRatio=function(){return this.width/this.height};e.lb=function(){return!(this.width*this.height)};e.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
e.ca=function(a){return this.width<=a.width&&this.height<=a.height};e.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};e.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Kb(a,b){var c=p(void 0)?void 0:b;a.width*=b;a.height*=c;return a}e.Jb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Kb(this,a)};
e.Kb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Kb(this,a)};function Lb(a){return a?new U(V(a)):pa||(pa=new U)}function Mb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Nb(document,"*",a,b);return d||null}
function Ob(a,b,c,d){a=d||a;var f=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(f||c))return a.querySelectorAll(f+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(f){a={};for(var g=d=0,h;h=b[g];g++)f==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(f||"*");if(c){a={};for(g=d=0;h=b[g];g++){f=h.className;var k;if(k="function"==typeof f.split)k=0<=u(f.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Nb(a,b,c,d){var f=d||a,g=b&&"*"!=b?String(b).toUpperCase():"";return f.querySelectorAll&&f.querySelector&&(g||c)?f.querySelector(g+(c?"."+c:"")):Ob(a,b,c,d)[0]||null}function Pb(a,b){Fa(b,function(b,d){b&&"object"==typeof b&&b.w&&(b=b.v());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Qb.hasOwnProperty(d)?a.setAttribute(Qb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}
var Qb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Sb(a){a=a.document;a=W(a)?a.documentElement:a.body;return new Jb(a.clientWidth,a.clientHeight)}function Tb(a){return a.scrollingElement?a.scrollingElement:!Oa&&W(a)?a.documentElement:a.body||a.documentElement}
function X(a){return a.parentWindow||a.defaultView}function Ub(a,b,c,d){function f(c){c&&b.appendChild(n(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];r(g)&&!Vb(g)?v(Wb(g)?sa(g):g,f):f(g)}}function W(a){return"CSS1Compat"==a.compatMode}function Xb(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Yb(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function Zb(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}
function Vb(a){return t(a)&&0<a.nodeType}function $b(a){return t(a)&&1==a.nodeType}function ac(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function bc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return cc(b,a)}function cc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}
function V(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function dc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else Xb(a),a.appendChild(V(a).createTextNode(String(b)))}function ec(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||ec(a,b,c,d))return!0;a=a.nextSibling}return!1}
var fc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},gc={IMG:" ",BR:"\n"};function hc(a){return ic(a)&&jc(a)}function ic(a){return y&&!z("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function jc(a){a=a.tabIndex;return p(a)&&0<=a&&32768>a}
function kc(a){if(Fb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];lc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Fb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function lc(a,b,c){if(!(a.nodeName in fc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in gc)b.push(gc[a.nodeName]);else for(a=a.firstChild;a;)lc(a,b,c),a=a.nextSibling}function Wb(a){if(a&&"number"==typeof a.length){if(t(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==q(a))return"function"==typeof a.item}return!1}
function mc(a,b,c,d){if(!b&&!c)return null;var f=b?String(b).toUpperCase():null;return nc(a,function(a){var b;(b=!f||a.nodeName==f)&&!(b=!c)&&(b=n(a.className))&&(a=a.className.split(/\s+/),b=0<=u(a,c));return b},!0,d)}function nc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function U(a){this.a=a||l.document||document}e=U.prototype;e.pa=Lb;e.Lb=function(a){this.a=a};e.la=function(){return this.a};
e.I=function(a){return n(a)?this.a.getElementById(a):a};e.Ka=function(a){return n(a)?this.a.getElementById(a):a};e.S=U.prototype.I;e.cb=function(a,b){return(b||this.a).getElementsByTagName(String(a))};e.J=function(a,b,c){return Ob(this.a,a,b,c)};e.ra=function(a,b,c){return Nb(this.a,a,b,c)};e.sa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Ob(document,"*",a,b)};e.qa=function(a,b){return Mb(a,b||this.a)};
e.La=function(a,b){return Mb(a,b||this.a)};e.T=U.prototype.J;e.Ob=Pb;e.Pa=function(a){return Sb(a||X(this.a)||window)};e.ma=function(){var a=X(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Sb(a).height,W(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var f=d.offsetHeight;d.clientHeight!=f&&(b=c.scrollHeight,f=c.offsetHeight);c=b>a?b>f?b:f:b<f?b:f}else c=0}return c};
e.H=function(a,b,c){var d=this.a,f=arguments,g=String(f[0]),h=f[1];if(!Db&&h&&(h.name||h.type)){g=["<",g];h.name&&g.push(' name="',Ia(h.name),'"');if(h.type){g.push(' type="',Ia(h.type),'"');var k={};Ha(k,h);delete k.type;h=k}g.push(">");g=g.join("")}g=d.createElement(g);h&&(n(h)?g.className=h:"array"==q(h)?g.className=h.join(" "):Pb(g,h));2<f.length&&Ub(d,g,f,2);return g};e.U=U.prototype.H;e.bb=function(a){return this.a.createTextNode(String(a))};
e.Y=function(a,b,c){var d=this.a;c=!!c;for(var f=d.createElement("TABLE"),g=f.appendChild(d.createElement("TBODY")),h=0;h<a;h++){for(var k=d.createElement("TR"),C=0;C<b;C++){var D=d.createElement("TD");c&&dc(D,"\u00a0");k.appendChild(D)}g.appendChild(k)}return f};
e.Ib=function(a){var b=this.a;var c=b.createElement("DIV");y?(a=ab(bb,a),Ib(c,Za(a)),c.removeChild(c.firstChild)):Ib(c,Za(a));if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};e.ub=function(){return W(this.a)};e.oa=function(){return Tb(this.a)};
e.na=function(){var a=this.a,b=Tb(a);a=X(a);return y&&z("10")&&a.pageYOffset!=b.scrollTop?new T(b.scrollLeft,b.scrollTop):new T(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};e.ea=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};e.Za=function(a,b){a.appendChild(b)};e.Ya=function(a,b){Ub(V(a),a,arguments,1)};e.$a=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
e.Gb=Xb;e.tb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};e.sb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};e.rb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};e.eb=Yb;e.fb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};e.da=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return Yb(a)}};
e.ja=function(a){return Eb&&void 0!=a.children?a.children:qa(a.childNodes,function(a){return 1==a.nodeType})};e.ta=function(a){return m(a.firstElementChild)?a.firstElementChild:Zb(a.firstChild,!0)};e.xa=function(a){return m(a.lastElementChild)?a.lastElementChild:Zb(a.lastChild,!1)};e.za=function(a){return m(a.nextElementSibling)?a.nextElementSibling:Zb(a.nextSibling,!0)};e.Ia=function(a){return m(a.previousElementSibling)?a.previousElementSibling:Zb(a.previousSibling,!1)};
e.Aa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};e.Ja=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};e.yb=Vb;e.vb=$b;e.Bb=function(a){return t(a)&&a.window==a};e.Ha=function(a){var b;if(Gb&&!(y&&z("9")&&!z("10")&&l.SVGElement&&a instanceof l.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return $b(b)?b:null};
e.ab=ac;
e.W=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(y&&!(9<=Number(A))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var f=a.parentNode,g=b.parentNode;return f==g?cc(a,b):!c&&ac(f,b)?-1*bc(a,b):!d&&ac(g,a)?bc(b,a):(c?a.sourceIndex:f.sourceIndex)-(d?b.sourceIndex:g.sourceIndex)}d=V(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(l.Range.START_TO_END,a)};e.$=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],f=Infinity;for(b=0;b<c;b++){for(var g=[],h=arguments[b];h;)g.unshift(h),h=h.parentNode;d.push(g);f=Math.min(f,g.length)}g=null;for(b=0;b<f;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return g;g=h}return g};e.Fa=V;e.ua=function(a){return a.contentDocument||a.contentWindow.document};
e.va=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?X(c):window}else d=null;b=d}return b}catch(f){}return null};e.Rb=dc;e.Ea=function(a){if("outerHTML"in a)return a.outerHTML;var b=V(a).createElement("DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};e.aa=function(a,b){var c=[];return ec(a,b,c,!0)?c[0]:void 0};e.ba=function(a,b){var c=[];ec(a,b,c,!1);return c};e.xb=hc;e.Mb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
e.wb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!ic(a)||jc(a)):hc(a))&&y){var c;"function"!=q(a.getBoundingClientRect)||y&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};e.Na=kc;e.Ca=function(a){return kc(a).length};
e.Da=function(a,b){b=b||V(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(kc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
e.Ba=function(a,b,c){a=[a];for(var d=0,f=null;0<a.length&&d<b;)if(f=a.pop(),!(f.nodeName in fc))if(3==f.nodeType){var g=f.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=g.length}else if(f.nodeName in gc)d+=gc[f.nodeName].length;else for(g=f.childNodes.length-1;0<=g;g--)a.push(f.childNodes[g]);t(c)&&(c.Fb=f?f.nodeValue.length+b-d-1:0,c.node=f);return f};e.zb=Wb;e.ha=mc;e.ga=function(a,b,c){return mc(a,null,b,c)};e.fa=nc;e.ia=function(a){return a.getContext("2d")};var oc={};function pc(a,b){var c=oc[a];if(void 0!==c&&(!c.A||Date.now()<=c.A+3E5))return c.p;c=new Promise(function(a,c){b.onload=function(){return a(b)};b.onerror=function(a){b.parentNode&&b.parentNode.removeChild(b);c(a)};document.head.appendChild(b)});var d={A:0,p:c};c.catch(function(){return d.A=+new Date});oc[a]=d;return c};function Y(a){var b=HTMLElement.call(this)||this;a&&(n(a)&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ha(Y,HTMLElement);e=Y.prototype;e.connectedCallback=function(){qc(this)};e.B=function(){return""};function qc(a){var b=a.B();!a.hasAttribute("ds-is")&&b&&a.setAttribute("ds-is",b)}e.Ub=function(){console.warn(this.tagName,"has not implemented update")};
e.X=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};e.Db=function(a,b){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&this.appendChild(document.importNode(b,!0))};Y.prototype.connectedCallback=Y.prototype.connectedCallback;function rc(a){if(!t(a))return String(a);if(a instanceof S){if(a.a===wb)return a.b;if(a.a===yb)return Ia(a.b)}return"zSoyz"}var sc={};var tc="autohide autoplay controls enablejsapi end hl rel showinfo start video-id".split(" "),uc=["listType","list"],vc=null,wc=!1;function Z(){var a=Y.call(this)||this;a.a=null;a.b=null;return a}ha(Z,Y);e=Z.prototype;e.B=function(){return"youtube"};
e.connectedCallback=function(){qc(this);xc(this);Z.f&&this.C();var a=this.F.bind(this),b=this.C.bind(this);if(m(window.YT))var c=!0;else{Z.b||(Z.b=[]);Z.a||(Z.a=[]);Z.b.push(a);Z.a.push(b);if(!vc){a=yc;b=["onYouTubeIframeAPIReady"];var d=l;b[0]in d||"undefined"==typeof d.execScript||d.execScript("var "+b[0]);for(var f;b.length&&(f=b.shift());)!b.length&&m(a)?d[f]=a:d[f]&&d[f]!==Object.prototype[f]?d=d[f]:d=d[f]={};c=void 0===c?null:c;f=new J("//www.youtube.com/iframe_api",void 0);a=document.createElement("script");
a.src=f.toString();c&&(a.type=c);vc=pc(f.toString(),a);vc.catch(zc)}c=!1}c&&this.F()};
e.F=function(){var a=this,b=document.createElement("div");this.appendChild(b);var c={origin:(new URL(document.location.toString())).origin};tc.forEach(function(b){a.hasAttribute(b)&&(c[b]=a.getAttribute(b))});uc.forEach(function(b){a.hasAttribute(b)&&(c[b]=a.getAttribute(b))});var d={playerVars:c,events:{onReady:this.L.bind(this),onStateChange:this.M.bind(this),onError:this.K.bind(this)}};this.hasAttribute("video-id")&&(d.videoId=this.getAttribute("video-id"));this.a=new YT.Player(b,d)};
e.attributeChangedCallback=function(a,b,c){if(this.a&&"action"===a)switch(c){case "play":this.a.playVideo();break;case "pause":this.a.pauseVideo();break;case "stop":this.a.stopVideo()}};e.L=function(a){"play"===this.getAttribute("action")&&a.target.playVideo()};
e.M=function(a){if(m(a)&&m(a.data)&&m(a.target)){var b=a.data,c=a.target;switch(b){case YT.PlayerState.PLAYING:this.setAttribute("action","play");a=null===this.b?"Video Start":"Video Resume";break;case YT.PlayerState.PAUSED:this.setAttribute("action","pause");a="Video Paused";break;case YT.PlayerState.ENDED:this.removeAttribute("action");a="Video Finished";break;default:return}this.b=b;b=c.getVideoData().video_id;c=c.getCurrentTime();p(c)&&(c=Math.floor(c));this.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",action:a,label:b,value:c},bubbles:!0}))}};e.K=function(){};
e.C=function(){var a={videoId:String(this.getAttribute("video-id"))};a=encodeURIComponent(String(String((a||sc).videoId)));Bb.lastIndex=0;a=Bb.test(a)?a.replace(Bb,Cb):a;var b=Ab('<a href="//www.youtube.com/watch?v='+a+'" class="devsite-video-placeholder"><img src="/_static/images/video-placeholder.svg"/><span>This resource may not be available in your region.</span></a>');a=Lb().a.createElement("DIV");b=rc(b);Ib(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));this.appendChild(a)};
function yc(){Z.f=!1;var a=Z.b;delete Z.b;delete Z.a;a.forEach(function(a){return a.call()});delete window.onYouTubeIframeAPIReady}function zc(){Z.f=!0;var a=Z.a;delete Z.b;delete Z.a;a&&a.forEach(function(a){return a.call()})}e.disconnectedCallback=function(){this.a&&this.a.destroy()};
function xc(a){a.parentNode.classList.contains("video-wrapper")&&a.setAttribute("inline-small","");var b=a.querySelector(".devsite-embedded-youtube-video");if(b){tc.forEach(function(c){b.hasAttribute("data-"+c)&&a.setAttribute(c,b.getAttribute("data-"+c))});if(b.src){var c=new J(b.src);uc.forEach(function(b){var d=c.a.get(b);d&&a.setAttribute(b,d)})}a.removeChild(b)}}
ia.Object.defineProperties(Z,{f:{configurable:!0,enumerable:!0,get:function(){return wc},set:function(a){wc=a}},observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["action"]}}});Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.attributeChangedCallback=Z.prototype.attributeChangedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-youtube",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteYouTube",a)};}).call(this);
