(function(g){var window=this;var TDa=function(a,b,c){a.o.has(b);a.o.add(b);g.Ff(c,function(){g.Vxa(a,b)})},j5=function(a,b,c){var d=b.Aa();
g.U(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.gd(c?c:"mqdefault.jpg");var f=b instanceof g.CP&&b.lengthSeconds?g.MV(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.qR(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.CP?b.Da:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Nl||g.xV("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Dm(),is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+
c+")":""};b instanceof g.sR&&(d.playlist_length=b.getLength());a.update(d)},k5=function(a,b){g.nQ.call(this,{J:"div",
da:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},l5=function(a){g.W.call(this,{J:"div",
da:["ytp-upnext","ytp-player-content"],T:{"aria-label":"{{aria_label}}"},P:[{J:"div",N:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{J:"span",N:"ytp-upnext-top",P:[{J:"span",N:"ytp-upnext-header",ca:"Up Next"},{J:"span",N:"ytp-upnext-title",ca:"{{title}}"},{J:"span",N:"ytp-upnext-author",ca:"{{author}}"}]},{J:"a",N:"ytp-upnext-autoplay-icon",T:{role:"button",href:"{{url}}","aria-label":"Play next video"},P:[{J:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
P:[{J:"circle",N:"ytp-svg-autoplay-circle",T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{J:"circle",N:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{J:"path",N:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{J:"span",N:"ytp-upnext-bottom",P:[{J:"span",N:"ytp-upnext-cancel"},{J:"span",N:"ytp-upnext-paused",
ca:"Autoplay is paused"}]}]});this.G=null;var b=this.o["ytp-upnext-cancel"];this.G=new g.W({J:"button",da:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":"Cancel autoplay"},ca:"Cancel"});g.K(this,this.G);this.G.X("click",this.GQ,this);this.G.A(b);this.B=a;this.M=this.o["ytp-svg-autoplay-ring"];this.I=this.H=this.D=this.F=null;this.K=new g.V(this.Uo,5E3,this);g.K(this,this.K);this.L=0;this.R(this.o["ytp-upnext-autoplay-icon"],"click",this.KS);this.mE();this.R(a,"autonavvisibility",
this.mE);this.R(a,"mdxnowautoplaying",this.ZR);this.R(a,"mdxautoplaycanceled",this.aS);this.R(a,"mdxautoplayupnext",this.LG);3==this.B.getPresentingPlayerType()&&(a=(a=g.RU(g.MU(this.B)))?a.WK():null)&&this.LG(a)},m5=function(a,b){if(!a.D){g.sF("a11y-announce","Up Next "+a.F.title);
a.L=g.IH();a.D=new g.V((0,g.A)(a.gt,a,b),25);a.gt(b);var c=b||g.Y(a.B).experiments.A("autoplay_time")||1E4;a.B.Ba("onAutonavCoundownStarted",c)}g.Dr(a.element,"ytp-upnext-autoplay-paused")},o5=function(a){n5(a);
a.L=g.IH();a.gt();g.T(a.element,"ytp-upnext-autoplay-paused")},n5=function(a){a.D&&(a.D.dispose(),a.D=null)},p5=function(a,b){b=void 0===b?!1:b;
if(g.Y(a.B).experiments.o("autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.F.Aa(),a.Uo(),a.H=new Notification("Up Next",{body:c.title,icon:c.gd()}),a.I=a.R(a.H,"click",a.BS),a.K.start())}n5(a);a.B.nextVideo(!1,b)},UDa=function(a){k5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.B=new g.W({J:"div",N:"ytp-subscribe-card",P:[{J:"img",N:"ytp-author-image",T:{src:b.Pk}},{J:"div",N:"ytp-subscribe-card-right",P:[{J:"div",N:"ytp-author-name",ca:b.author},{J:"div",N:"html5-subscribe-button-container"}]}]});g.K(this,this.B);this.B.A(this.element);this.D=new g.y_("Subscribe",null,"Unsubscribe",null,!0,!1,b.tl,b.subscribed,"trailer-endscreen",null,null,a);g.K(this,this.D);this.D.A(this.B.o["html5-subscribe-button-container"]);this.hide()},q5=function(a){var b=
g.Y(a),c=g.aM||g.Kf?{style:"will-change: opacity"}:void 0,d=b.o,e=["ytp-videowall-still"];
b.A&&e.push("ytp-videowall-show-text");g.W.call(this,{J:"a",da:e,T:{href:"{{url}}",target:d?b.F:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},P:[{J:"div",N:"ytp-videowall-still-image",T:{style:"{{background}}"}},{J:"span",N:"ytp-videowall-still-info",P:[{J:"span",N:"ytp-videowall-still-info-bg",P:[{J:"span",N:"ytp-videowall-still-info-content",T:c,P:[{J:"span",N:"ytp-videowall-still-info-title",ca:"{{title}}"},{J:"span",N:"ytp-videowall-still-info-author",
ca:"{{author_and_views}}"},{J:"span",N:"ytp-videowall-still-info-live",ca:"Live"},{J:"span",N:"ytp-videowall-still-info-duration",ca:"{{duration}}"}]}]}]},{J:"span",da:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],P:[{J:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{J:"span",N:"ytp-videowall-still-listlabel-length",P:[" (",{J:"span",ca:"{{playlist_length}}"},")"]}]},{J:"span",da:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],P:[{J:"span",
N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{J:"span",N:"ytp-videowall-still-listlabel-length",ca:" (50+)"}]}]});this.G=d;this.B=a;this.D=null;this.F=new g.lH(this);g.K(this,this.F);this.X("click",this.I);this.X("keypress",this.K);this.F.R(a,"videodatachange",this.H);g.Y(a).ia&&TDa(a.app.ma,this.element,this);this.H()},r5=function(a){k5.call(this,a,"videowall-endscreen");
this.L=a;this.H=0;this.D=[];this.I=this.F=this.G=null;this.K=this.aa=!1;this.Y=null;this.Z=new g.lH(this);g.K(this,this.Z);this.M=new g.V(g.Ma(g.T,this.element,"ytp-show-tiles"),0);g.K(this,this.M);var b=new g.W({J:"button",da:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":"Previous"},P:[g.FV()]});g.K(this,b);b.A(this.element);b.X("click",this.wO,this);this.O=new g.iQ({J:"div",N:"ytp-endscreen-content"});g.K(this,this.O);this.O.A(this.element);b=new g.W({J:"button",da:["ytp-button","ytp-endscreen-next"],
T:{"aria-label":"Next"},P:[g.GV()]});g.K(this,b);b.A(this.element);b.X("click",this.vO,this);this.B=new l5(a);g.K(this,this.B);g.dV(this.player,this.B.element,4);this.hide()},s5=function(a){return g.fV(a.player)&&a.bA()&&!a.I},VDa=function(a,b){return(0,g.I)(b.suggestions,function(b){b=g.YV(g.Y(a.L),b);
g.K(a,b);return b})},t5=function(a){var b=a.cg();
b!=a.aa&&(a.aa=b,a.player.U("autonavvisibility"))},u5=function(a){g.mV.call(this,a);
this.o=null;this.A=new g.lH(this);g.K(this,this.A);this.C=g.Y(a);WDa(a)?this.o=new r5(this.player):this.C.Ka?this.o=new UDa(this.player):this.o=new k5(this.player);g.K(this,this.o);g.dV(this.player,this.o.element,4);this.FF();this.A.R(a,"videodatachange",this.FF,this);this.A.R(a,g.pR("endscreen"),this.KN,this);this.A.R(a,"crx_endscreen",this.LN,this)},WDa=function(a){a=g.Y(a);
return a.Ia&&!a.Ka};
g.r(k5,g.nQ);k5.prototype.create=function(){this.created=!0};
k5.prototype.destroy=function(){this.created=!1};
k5.prototype.bA=function(){return!1};
k5.prototype.cg=function(){return!1};g.r(l5,g.W);g.h=l5.prototype;g.h.Uo=function(){this.H&&(this.K.stop(),this.La(this.I),this.I=null,this.H.close(),this.H=null)};
g.h.mE=function(){g.mQ(this,this.B.cg())};
g.h.BS=function(){window.focus();this.Uo()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.gt=function(a){a=a||g.Y(this.B).experiments.A("autoplay_time")||1E4;var b=Math.min(g.IH()-this.L,a);a=Math.min(b/a,1);this.M.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.B.getPresentingPlayerType()?p5(this,!0):this.D&&this.D.start()};
g.h.KS=function(a){!g.we(this.G.element,g.$G(a))&&g.$V(a,this.B)&&p5(this)};
g.h.GQ=function(){g.OU(this.B,!0)};
g.h.ZR=function(a){this.B.getPresentingPlayerType();this.show();m5(this,a)};
g.h.LG=function(a){this.B.getPresentingPlayerType();this.F&&this.F.Aa().videoId==a.Aa().videoId||(this.F=a,j5(this,a,"hqdefault.jpg"))};
g.h.aS=function(){this.B.getPresentingPlayerType();n5(this);this.hide()};
g.h.W=function(){n5(this);this.Uo();g.W.prototype.W.call(this)};g.r(UDa,k5);g.r(q5,g.W);q5.prototype.Wk=function(){g.hV(this.B,this.element);var a=this.D.Aa().videoId,b=this.D.getPlaylistId();g.M0(this.B.app,a,this.D.Kd,b,void 0,void 0,void 0)};
q5.prototype.I=function(a){g.$V(a,this.B,this.G,this.D.Kd||void 0)&&this.Wk()};
q5.prototype.K=function(a){switch(a.keyCode){case 13:case 32:g.eH(a)||(this.Wk(),g.dH(a))}};
q5.prototype.H=function(){var a=this.B.getVideoData(),b=g.Y(this.B);this.G=a.Jc?!1:b.o};g.r(r5,k5);g.h=r5.prototype;g.h.create=function(){k5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.G=VDa(this,a),this.F=a);this.Wg();this.Z.R(this.player,"appresize",this.Wg);this.Z.R(this.player,"onVideoAreaChange",this.Wg);this.Z.R(this.player,"videodatachange",this.xO);this.Z.R(this.player,"autonavchange",this.cw);this.Z.R(this.player,"autonavcancel",this.uO);a=this.F.autonavState;a!=this.Y&&this.cw(a);this.Z.R(this.element,"transitionend",this.kU)};
g.h.destroy=function(){g.nH(this.Z);g.Hf(this.D);this.D=[];this.G=null;k5.prototype.destroy.call(this);g.Dr(this.element,"ytp-show-tiles");this.M.stop();this.Y=this.F.autonavState};
g.h.bA=function(){return 1!=this.F.autonavState};
g.h.show=function(){k5.prototype.show.call(this);g.Dr(this.element,"ytp-show-tiles");g.Y(this.player).A?g.uv(this.M):this.M.start();(this.K||this.I&&this.I!=this.F.clientPlaybackNonce)&&g.OU(this.player,!1);s5(this)?(t5(this),2==this.F.autonavState?g.Y(this.player).experiments.o("fast_autonav_in_background")&&3==this.player.getVisibilityState()?p5(this.B,!0):m5(this.B):3==this.F.autonavState&&o5(this.B)):(g.OU(this.player,!0),t5(this))};
g.h.hide=function(){k5.prototype.hide.call(this);o5(this.B);t5(this)};
g.h.kU=function(a){g.$G(a)==this.element&&this.Wg()};
g.h.Wg=function(){if(this.G&&this.G.length){g.T(this.element,"ytp-endscreen-paginate");var a=g.XU(this.L,!0),b=g.yQ(this.L);b&&(b=b.Yc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.G.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,t=e/2,w=b<=f-2&&n>=t*m,z=e<=k-2&&n>=p*m;if((p+1)/t*d/c>c/(p/(t+1)*d)&&z)n-=p*m,e+=2;else if(w)n-=t*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Id(a.width/m||1,1,1.21);n*=g.Id(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.gi(a,m,n);g.Ph(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.B;f=this.G[0];c.F=f;j5(c,f,"hqdefault.jpg");g.U(this.element,"ytp-endscreen-takeover",s5(this));t5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,t=0,d&&f>=b-2&&k>=e-
2?t=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(t=2):t=2),p=g.Kd(p+this.H,l),0!=t){w=this.D[c];w||(w=new q5(this.player),this.D[c]=w,a.appendChild(w.element));z=Math.floor(n*k/e);var E=Math.floor(m*f/b),G=Math.floor(n*(k+t)/e)-z-4,N=Math.floor(m*(f+t)/b)-E-4;g.Wh(w.element,E,z);g.gi(w.element,N,G);g.Ph(w.element,"transitionDelay",(k+f)/20+"s");g.U(w.element,"ytp-videowall-still-mini",1==t);g.U(w.element,"ytp-videowall-still-large",2<t);t=w;p=this.G[p];t.D!=p&&(t.D=p,j5(t,p,g.Br(t.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),w=(p=p.Kd)&&p.itct)&&(p=t.B,g.Y(p).ia&&(t=t.element,p.app.ma.o.has(t),w&&(t.visualElement=g.gI(w))));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.D.length-1;b>=c;b--)e=this.D[b],g.qe(e.element),g.Gf(e);this.D.length=c}};
g.h.xO=function(){var a=this.player.getVideoData();this.F!=a&&(this.H=0,this.G=VDa(this,a),this.F=a,this.Wg())};
g.h.vO=function(){this.H+=this.D.length;this.Wg()};
g.h.wO=function(){this.H-=this.D.length;this.Wg()};
g.h.XM=function(){return!!this.B.D};
g.h.cw=function(a){1==a?(this.K=!1,this.I=this.F.clientPlaybackNonce,n5(this.B),this.C&&this.Wg()):(this.K=!0,this.C&&s5(this)&&(2==a?m5(this.B):3==a&&o5(this.B)))};
g.h.uO=function(a){if(a){for(a=0;a<this.D.length;a++)g.iV(this.L,this.D[a].element,!0);this.cw(1)}else this.I=null,this.K=!1;this.Wg()};
g.h.cg=function(){return this.C&&s5(this)};g.r(u5,g.mV);g.h=u5.prototype;g.h.Qn=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!WDa(this.player)||b;a=a.nd;var c=g.u0(this.player.app);return b&&!a&&!c};
g.h.cg=function(){return this.o.cg()};
g.h.SM=function(){return this.cg()?this.o.XM():!1};
g.h.W=function(){g.bV(this.player,"endscreen");g.mV.prototype.W.call(this)};
g.h.load=function(){g.mV.prototype.load.call(this);this.o.show()};
g.h.unload=function(){g.mV.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.KN=function(a){this.Qn()&&(this.o.created||this.o.create(),"load"==a.getId()&&this.load())};
g.h.LN=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.FF=function(){g.bV(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.nR(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.K(this,a);var b=new g.nR(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.K(this,b);g.ZU(this.player,[a,b])};g.WZ.endscreen=u5;})(_yt_player);
